# No installer, credential lookup, dependency bootstrap or compilation.
# Only public metadata downloads and explicitly listed host/version queries.
set(CMAKE_TLS_VERIFY ON)
set(evidence_dir "${CMAKE_BINARY_DIR}/evidence")
file(MAKE_DIRECTORY "${evidence_dir}/public-metadata")
file(READ "${CMAKE_CURRENT_LIST_DIR}/public-metadata-lock.json" artifact_lock)
file(SHA256 "${CMAKE_CURRENT_LIST_DIR}/public-metadata-lock.json" artifact_lock_sha)
string(TIMESTAMP capture_utc "%Y-%m-%dT%H:%M:%SZ" UTC)
set(report "{\"schema\":1,\"dependency_build_status\":\"blocked_not_attempted\",\"observations\":{}}")
set(summary "# Linux dependency preflight — throwaway\n\n**Dependency build: BLOCKED / NOT ATTEMPTED.** No Qt installer, login, terms acceptance, vcpkg or compiler build was executed. A green workflow means this capture completed, not that the dependency slice passed.\n\n")
set(metadata_errors "")

function(json_string output value)
    string(REPLACE "\\" "\\\\" value "${value}")
    string(REPLACE "\"" "\\\"" value "${value}")
    string(REPLACE "\r" "\\r" value "${value}")
    string(REPLACE "\n" "\\n" value "${value}")
    string(REPLACE "\t" "\\t" value "${value}")
    set(${output} "\"${value}\"" PARENT_SCOPE)
endfunction()

function(observe key state detail)
    json_string(state_json "${state}")
    json_string(detail_json "${detail}")
    set(entry "{}")
    string(JSON entry SET "${entry}" status "${state_json}")
    string(JSON entry SET "${entry}" detail "${detail_json}")
    string(JSON next_report SET "${report}" observations "${key}" "${entry}")
    set(report "${next_report}" PARENT_SCOPE)
    set(summary "${summary}### ${key}: ${state}\n\n${detail}\n\n" PARENT_SCOPE)
endfunction()

function(host_command key)
    execute_process(COMMAND ${ARGN} RESULT_VARIABLE result OUTPUT_VARIABLE output
        ERROR_VARIABLE error TIMEOUT 15 OUTPUT_STRIP_TRAILING_WHITESPACE)
    # Version / narrowly scoped host output only. No environment or user logs.
    string(SUBSTRING "${output}" 0 4096 output)
    if(result STREQUAL "0")
        observe("${key}" "observed" "${output}")
    else()
        observe("${key}" "unavailable_or_partial" "Exit: ${result}\n${output}")
    endif()
    set(report "${report}" PARENT_SCOPE)
    set(summary "${summary}" PARENT_SCOPE)
endfunction()

function(tool_version tool)
    unset(tool_path)
    find_program(tool_path NAMES "${tool}" NO_CACHE)
    if(tool_path)
        host_command("tool_${tool}" "${tool_path}" --version)
    else()
        observe("tool_${tool}" "missing" "Not found on PATH; no installation attempted.")
    endif()
    set(report "${report}" PARENT_SCOPE)
    set(summary "${summary}" PARENT_SCOPE)
endfunction()

function(fetch_public key url output_name output_var)
    set(path "${evidence_dir}/public-metadata/${output_name}")
    file(DOWNLOAD "${url}" "${path}" STATUS download_status
        TIMEOUT 45 INACTIVITY_TIMEOUT 15 TLS_VERIFY ON)
    list(GET download_status 0 result)
    if(NOT result EQUAL 0)
        observe("${key}" "download_failed" "Public URL: ${url}; status: ${download_status}")
        set(metadata_errors "${metadata_errors};${key}: download failed" PARENT_SCOPE)
        set(${output_var} "" PARENT_SCOPE)
    else()
        file(SHA256 "${path}" digest)
        file(READ "${path}" content)
        observe("${key}" "public_metadata_fetched" "URL: ${url}\nMetadata SHA-256: ${digest}")
        set(${output_var} "${content}" PARENT_SCOPE)
    endif()
    set(report "${report}" PARENT_SCOPE)
    set(summary "${summary}" PARENT_SCOPE)
endfunction()

observe(capture "preflight_only" "UTC: ${capture_utc}\nCMake: ${CMAKE_VERSION}\nHost: ${CMAKE_HOST_SYSTEM_NAME} ${CMAKE_HOST_SYSTEM_VERSION}\nCandidate lock SHA-256: ${artifact_lock_sha}\nRuns before project(); project languages remain NONE.")
foreach(name ImageOS ImageVersion RUNNER_OS RUNNER_ARCH GITHUB_SHA GITHUB_RUN_ID GITHUB_RUN_ATTEMPT)
    if(DEFINED ENV{${name}})
        observe("ci_${name}" "observed" "$ENV{${name}}")
    endif()
endforeach()
cmake_host_system_information(RESULT host_cores QUERY NUMBER_OF_LOGICAL_CORES)
cmake_host_system_information(RESULT host_memory QUERY TOTAL_PHYSICAL_MEMORY)
observe(host_resources "snapshot_only" "Logical processors: ${host_cores}; total physical memory: ${host_memory} MiB. Not a performance reference host or capacity guarantee.")
foreach(tool git ninja gcc g++ make pkg-config autoconf automake libtool nasm meson python3 curl tar unzip zip)
    tool_version("${tool}")
endforeach()
if(CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
    if(EXISTS "/etc/os-release")
        file(STRINGS "/etc/os-release" os_identity REGEX "^(ID|VERSION_ID|PRETTY_NAME)=")
        string(REPLACE ";" "\n" os_identity "${os_identity}")
        observe(distribution "observed_not_immutable" "${os_identity}")
    endif()
    host_command(kernel uname -srmo)
    host_command(glibc getconf GNU_LIBC_VERSION)
    host_command(disk_free df -Pk "${CMAKE_BINARY_DIR}")
    host_command(host_packages dpkg-query -W [=[-f=${binary:Package}\t${Version}\n]=]
        libc6 libstdc++6 gcc g++ cmake ninja-build git pkg-config
        autoconf automake libtool nasm meson curl tar unzip zip
        libgl1 libegl1 libfontconfig1 libfreetype6 libx11-6 libx11-xcb1
        libxcb1 libxcb-cursor0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1
        libxcb-randr0 libxcb-render-util0 libxcb-xkb1 libxkbcommon0
        libxkbcommon-x11-0 libdbus-1-3 libatspi2.0-0t64 libwayland-client0 xvfb)
else()
    observe(linux_execution "not_executed" "This is public metadata inspection on ${CMAKE_HOST_SYSTEM_NAME}; no Linux result follows.")
endif()

# The workflow passes only a boolean, never the JWT itself. This cannot prove validity.
if("$ENV{HIKARI_QT_AUTH_DECLARED}" STREQUAL "true")
    observe(qt_auth "declared_not_validated" "CI reports a nonempty QT_INSTALLER_JWT_TOKEN secret. Token was not supplied to this process or validated. No account files read.")
else()
    observe(qt_auth "missing_or_not_declared" "No CI secret-presence signal. An authorized installer account is required for the future provisioner. No account files read.")
endif()
observe(qt_terms "not_authorized_by_this_probe" "This preflight has no license/obligation acceptance scope. It cannot execute an installer even when an account is available.")

string(JSON installer_url GET "${artifact_lock}" installer url)
string(JSON installer_sha_url GET "${artifact_lock}" installer sha256_url)
string(JSON installer_sha GET "${artifact_lock}" installer declared_sha256)
fetch_public(installer_checksum "${installer_sha_url}" "installer.sha256" installer_checksum)
if(installer_checksum)
    string(REGEX MATCH "^[0-9a-fA-F]+" published_sha "${installer_checksum}")
    if(NOT published_sha STREQUAL installer_sha)
        list(APPEND metadata_errors "installer checksum declaration changed")
        observe(installer_identity "mismatch" "Published checksum does not match the committed candidate. Stop; do not adopt the new value.")
    else()
        observe(installer_identity "declared_sha256_matches" "Versioned URL: ${installer_url}\nDeclared binary SHA-256: ${installer_sha}\nBinary not downloaded or executed; digest is publisher metadata, not a local binary verification.")
    endif()
endif()

string(JSON updates_url GET "${artifact_lock}" qt_package updates_url)
string(JSON updates_sha GET "${artifact_lock}" qt_package updates_sha256)
string(JSON package_id GET "${artifact_lock}" qt_package id)
string(JSON package_version GET "${artifact_lock}" qt_package version)
string(JSON package_dependencies GET "${artifact_lock}" qt_package dependencies)
fetch_public(qt_repository_metadata "${updates_url}" "Updates.xml" updates)
if(updates)
    file(SHA256 "${evidence_dir}/public-metadata/Updates.xml" current_updates_sha)
    if(NOT current_updates_sha STREQUAL updates_sha)
        list(APPEND metadata_errors "Qt repository metadata changed")
        observe(qt_package "mismatch" "Expected metadata SHA-256 ${updates_sha}; observed ${current_updates_sha}. Candidate must be reviewed again.")
    else()
        observe(qt_package "exact_metadata_snapshot_matches" "Package: ${package_id}\nVersion: ${package_version}\nDeclared dependencies: ${package_dependencies}\nThis locks one metadata snapshot, not the full installer dependency closure or upstream retention.")
    endif()
endif()

string(JSON archive_count LENGTH "${artifact_lock}" qt_package archives)
math(EXPR last_archive "${archive_count} - 1")
foreach(index RANGE 0 ${last_archive})
    string(JSON archive_url GET "${artifact_lock}" qt_package archives ${index} url)
    string(JSON checksum_url GET "${artifact_lock}" qt_package archives ${index} sha256_url)
    string(JSON expected_sha GET "${artifact_lock}" qt_package archives ${index} declared_sha256)
    fetch_public("archive_${index}_checksum" "${checksum_url}" "archive-${index}.sha256" checksum)
    if(checksum)
        string(REGEX MATCH "^[0-9a-fA-F]+" published_sha "${checksum}")
        if(NOT published_sha STREQUAL expected_sha)
            list(APPEND metadata_errors "archive ${index} checksum declaration changed")
            observe("archive_${index}" "mismatch" "Published checksum differs from the committed candidate. No archive fetched.")
        else()
            observe("archive_${index}" "declared_sha256_matches" "URL: ${archive_url}\nDeclared binary SHA-256: ${expected_sha}\nArchive not downloaded or installed.")
        endif()
    endif()
endforeach()

observe(artifact_closure "incomplete" "Eight base SDK archive identities are candidate-pinned. Parent/license/package scripts, Creator/docs/examples dependencies, repository redirects, retention and enforcement of the installer's actual consumed bytes remain unproved.")
observe(vcpkg_graph "not_provisioned" "Candidate research registry ee6a47dac031930715bea2e6dfb9ad60caaa5d83; no complete tool/registry/overlay lock is supplied here. No vcpkg executable invoked. Qt remains outside its graph.")
observe(ffms2_private_abi "not_built" "Required fork 45d5f72100d88c52acdd54bfedcc0315a44c735d plus indexing_additional.cpp blob be378044fff07bac704f04dc57caa4fc5f95691e need one owned recipe and compatible FFmpeg selection. No distro-library substitute.")
observe(qualification "not_attempted" "No C++ SDK compile/link, Quick scene, Linguist round-trip, FFMS2 private extension, libass render, cold/warm reconstruction, deployment, corruption case, Fedora/Wayland/a11y or performance pass. Host image and tool versions are observed, not an immutable build environment.")

if(metadata_errors)
    observe(public_metadata_validation "failed" "${metadata_errors}")
else()
    observe(public_metadata_validation "passed_metadata_only" "Repository metadata and nine published binary checksum declarations match the candidate. Actual binary content and installer enforcement are unverified.")
endif()
file(WRITE "${evidence_dir}/report.json" "${report}\n")
file(WRITE "${evidence_dir}/report.md" "${summary}")
file(COPY "${CMAKE_CURRENT_LIST_DIR}/public-metadata-lock.json" DESTINATION "${evidence_dir}")
message(STATUS "Preflight evidence: ${evidence_dir}/report.md")
message(STATUS "DEPENDENCY BUILD BLOCKED / NOT ATTEMPTED")
if(metadata_errors)
    message(FATAL_ERROR "Public metadata validation failed; see preserved preflight evidence.")
endif()
if(HIKARI_REQUIRE_LINUX AND NOT CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux")
    message(FATAL_ERROR "linux-ci-preflight requires Linux. Use metadata-only-preflight for a clearly limited metadata check.")
endif()
