# Official Qt from a frozen, verified local repository mirror.
#
# The lock (cmake/locks/qt-<platform>.lock.json, written by tools/qt-lock) is
# the only authority. Objects are acquired into a local mirror and verified by
# SHA-256; the official installer then installs from that mirror alone. An
# installation is reused only while its stamp matches the lock's digest.
include_guard(GLOBAL)

function(_hikari_qt_entries lock base out_var)
    set(entries "")
    string(LENGTH "${base}" base_len)
    string(JSON n LENGTH "${lock}" roots)
    math(EXPR last "${n} - 1")
    foreach(i RANGE ${last})
        string(JSON url GET "${lock}" roots ${i} updates_xml url)
        string(JSON len GET "${lock}" roots ${i} updates_xml length)
        string(JSON sha GET "${lock}" roots ${i} updates_xml sha256)
        string(SUBSTRING "${url}" ${base_len} -1 path)
        list(APPEND entries "${path}|${url}|${len}|${sha}")
    endforeach()
    string(JSON n LENGTH "${lock}" objects)
    math(EXPR last "${n} - 1")
    foreach(i RANGE ${last})
        foreach(k path url length sha256)
            string(JSON ${k} GET "${lock}" objects ${i} ${k})
        endforeach()
        list(APPEND entries "${path}|${url}|${length}|${sha256}")
    endforeach()
    set(${out_var} "${entries}" PARENT_SCOPE)
endfunction()

function(_hikari_verify_file file length sha out_ok)
    set(ok FALSE)
    if(EXISTS "${file}")
        file(SIZE "${file}" actual_len)
        if(actual_len EQUAL length)
            file(SHA256 "${file}" actual_sha)
            if(actual_sha STREQUAL sha)
                set(ok TRUE)
            endif()
        endif()
    endif()
    set(${out_ok} ${ok} PARENT_SCOPE)
endfunction()

function(_hikari_json_list lock key out_var)
    set(values "")
    string(JSON n LENGTH "${lock}" ${key})
    if(n GREATER 0)
        math(EXPR last "${n} - 1")
        foreach(i RANGE ${last})
            string(JSON v GET "${lock}" ${key} ${i})
            list(APPEND values "${v}")
        endforeach()
    endif()
    set(${out_var} "${values}" PARENT_SCOPE)
endfunction()

# Acquire every locked object into <sdk>/qt-mirror-<platform>; verify-only mode
# fails on the first missing or changed object instead of fetching it.
function(hikari_qt_acquire platform)
    set(lock_file "${HIKARI_LOCK_DIR}/qt-${platform}.lock.json")
    file(READ "${lock_file}" lock)
    string(JSON complete GET "${lock}" complete)
    string(JSON nproblems LENGTH "${lock}" problems)
    if(NOT complete OR NOT nproblems EQUAL 0)
        message(FATAL_ERROR "Qt lock ${lock_file} is incomplete or records problems; regenerate and review it")
    endif()
    string(JSON base GET "${lock}" base)
    string(JSON inst_url GET "${lock}" installer url)
    string(JSON inst_len GET "${lock}" installer length)
    string(JSON inst_sha GET "${lock}" installer sha256)
    string(JSON inst_declared GET "${lock}" installer declared_sha256)
    string(JSON obj_bytes GET "${lock}" declared_bytes objects)
    if(NOT inst_sha STREQUAL inst_declared)
        message(FATAL_ERROR "Locked Qt installer digest differs from its declared SHA-256")
    endif()
    math(EXPR declared "${obj_bytes} + ${inst_len}")
    if(declared GREATER HIKARI_QT_ACQUIRE_LIMIT)
        message(FATAL_ERROR "Declared Qt acquisition ${declared} exceeds the ${HIKARI_QT_ACQUIRE_LIMIT}-byte bound")
    endif()

    set(mirror "${HIKARI_SDK_DIR}/qt-mirror-${platform}")
    get_filename_component(inst_name "${inst_url}" NAME)
    set(installer "${HIKARI_SDK_DIR}/qt-installer/${inst_name}")
    _hikari_qt_entries("${lock}" "${base}" entries)
    list(APPEND entries "@installer|${inst_url}|${inst_len}|${inst_sha}")

    set(fetched 0)
    set(expected "")
    set(report "path\tlength\tsha256\taction\n")
    foreach(e IN LISTS entries)
        string(REPLACE "|" ";" f "${e}")
        list(GET f 0 path)
        list(GET f 1 url)
        list(GET f 2 len)
        list(GET f 3 sha)
        if(path STREQUAL "@installer")
            set(dest "${installer}")
        else()
            set(dest "${mirror}/${path}")
            list(APPEND expected "${dest}")
        endif()
        _hikari_verify_file("${dest}" ${len} ${sha} ok)
        if(ok)
            set(action cached)
        elseif(HIKARI_QT_VERIFY_ONLY)
            file(APPEND "${HIKARI_EVIDENCE_DIR}/qt-verify-rejections.tsv" "${path}\t${len}\t${sha}\n")
            message(FATAL_ERROR "Qt mirror object missing or changed: ${path}")
        else()
            set(action downloaded)
            if(EXISTS "${dest}")
                set(action refetched-after-mismatch)
                file(REMOVE "${dest}")
            endif()
            math(EXPR fetched "${fetched} + ${len}")
            if(fetched GREATER HIKARI_QT_ACQUIRE_LIMIT)
                message(FATAL_ERROR "Qt acquisition exceeded its bound at ${path}")
            endif()
            file(DOWNLOAD "${url}" "${dest}" EXPECTED_HASH SHA256=${sha} TLS_VERIFY ON
                TIMEOUT 900 INACTIVITY_TIMEOUT 60 STATUS st)
            list(GET st 0 rc)
            _hikari_verify_file("${dest}" ${len} ${sha} ok)
            if(NOT rc EQUAL 0 OR NOT ok)
                file(REMOVE "${dest}")
                message(FATAL_ERROR "Locked Qt object rejected: ${path} (${st})")
            endif()
        endif()
        string(APPEND report "${path}\t${len}\t${sha}\t${action}\n")
    endforeach()
    if(NOT CMAKE_HOST_WIN32)
        file(CHMOD "${installer}" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE)
    endif()
    file(GLOB_RECURSE present LIST_DIRECTORIES false "${mirror}/*")
    list(REMOVE_ITEM present ${expected})
    if(present)
        message(FATAL_ERROR "Unlocked files in the Qt mirror: ${present}")
    endif()
    file(WRITE "${HIKARI_EVIDENCE_DIR}/qt-acquired.tsv" "${report}")
    message(STATUS "Qt mirror verified: ${mirror} (${fetched} bytes transferred)")
    set(HIKARI_QT_MIRROR "${mirror}" PARENT_SCOPE)
    set(HIKARI_QT_INSTALLER "${installer}" PARENT_SCOPE)
endfunction()

# Install from the verified mirror into <sdk>/qt-6.11.2-<platform>.
# Authentication: QT_INSTALLER_JWT_TOKEN if set (then a private HOME keeps the
# account file out of the user profile and is deleted afterwards); otherwise
# the installer uses the developer's existing Qt Account login. This code never
# reads, prints or caches the token or the account file.
function(hikari_qt_install platform)
    set(lock_file "${HIKARI_LOCK_DIR}/qt-${platform}.lock.json")
    file(READ "${lock_file}" lock)
    file(SHA256 "${lock_file}" lock_digest)
    set(target "${HIKARI_SDK_DIR}/qt-6.11.2-${platform}")
    set(stamp "${target}/.hikari-lock-sha256")
    if(EXISTS "${stamp}")
        file(READ "${stamp}" installed_digest)
        string(STRIP "${installed_digest}" installed_digest)
        if(installed_digest STREQUAL lock_digest)
            set(HIKARI_QT_ROOT "${target}" PARENT_SCOPE)
            return()
        endif()
        message(FATAL_ERROR "Qt at ${target} was installed from a different lock; remove it to reinstall")
    endif()
    if(EXISTS "${target}")
        message(FATAL_ERROR "${target} exists without a completed-install stamp; remove it to reinstall")
    endif()

    # Authorization covers the reviewed license bytes only.
    set(lic_dir "${HIKARI_SDK_DIR}/qt-license-check")
    file(REMOVE_RECURSE "${lic_dir}")
    string(JSON nroots LENGTH "${lock}" roots)
    math(EXPR last "${nroots} - 1")
    set(repos "")
    if(HIKARI_QT_REPOSITORY_BASE)
        set(repo_base "${HIKARI_QT_REPOSITORY_BASE}")
    else()
        file(TO_CMAKE_PATH "${HIKARI_QT_MIRROR}" mirror_path)
        if(CMAKE_HOST_WIN32)
            set(repo_base "file:///${mirror_path}/")
        else()
            set(repo_base "file://${mirror_path}/")
        endif()
    endif()
    foreach(i RANGE ${last})
        string(JSON suffix GET "${lock}" roots ${i} suffix)
        list(APPEND repos "${repo_base}${suffix}")
        if(suffix MATCHES "^all_os/license_agreements/")
            string(JSON meta GET "${lock}" roots ${i} metadata name)
            file(ARCHIVE_EXTRACT INPUT "${HIKARI_QT_MIRROR}/${suffix}${meta}" DESTINATION "${lic_dir}")
        endif()
    endforeach()
    string(JSON nlic LENGTH "${lock}" license_texts)
    math(EXPR last "${nlic} - 1")
    foreach(i RANGE ${last})
        string(JSON lf GET "${lock}" license_texts ${i} file)
        string(JSON ls GET "${lock}" license_texts ${i} sha256)
        file(SHA256 "${lic_dir}/${lf}" actual)
        if(NOT actual STREQUAL ls)
            message(FATAL_ERROR "Qt license text ${lf} changed since owner review (altqx/hikari#48); authorization does not cover it")
        endif()
    endforeach()
    file(REMOVE_RECURSE "${lic_dir}")
    list(JOIN repos "," repos_arg)
    _hikari_json_list("${lock}" requested packages)

    set(private "${HIKARI_SDK_DIR}/qt-install-private")
    file(REMOVE_RECURSE "${private}")
    file(MAKE_DIRECTORY "${private}/tmp" "${HIKARI_SDK_DIR}/qt-metadata-cache")
    set(saved_home "$ENV{HOME}")
    set(saved_tmpdir_defined FALSE)
    if(DEFINED ENV{TMPDIR})
        set(saved_tmpdir_defined TRUE)
        set(saved_tmpdir "$ENV{TMPDIR}")
    endif()
    set(saved_userprofile "$ENV{USERPROFILE}")
    if(DEFINED ENV{QT_INSTALLER_JWT_TOKEN} AND NOT "$ENV{QT_INSTALLER_JWT_TOKEN}" STREQUAL "")
        file(MAKE_DIRECTORY "${private}/home")
        set(ENV{HOME} "${private}/home")
        set(ENV{USERPROFILE} "${private}/home")
        set(auth "QT_INSTALLER_JWT_TOKEN (private HOME)")
    else()
        set(auth "existing Qt Account login")
    endif()
    if(NOT CMAKE_HOST_WIN32)
        set(ENV{QT_QPA_PLATFORM} "offscreen")
        set(ENV{TMPDIR} "${private}/tmp")
    endif()
    message(STATUS "Installing Qt 6.11.2 (${platform}) from the verified mirror; authentication: ${auth}")
    # No --default-answer/--accept-messages: an uncharacterized prompt reads EOF
    # or times out and the configure fails for review. Owner authorization for
    # the locked license set: altqx/hikari#48 issuecomment-5890780519.
    execute_process(COMMAND "${HIKARI_QT_INSTALLER}"
            --root "${target}"
            --cache-path "${HIKARI_SDK_DIR}/qt-metadata-cache"
            --set-temp-repository "${repos_arg}"
            --no-default-installations --no-force-installations
            --max-concurrent-operations 2
            --accept-licenses --accept-obligations --confirm-command
            --auto-answer "telemetry-question=No,AssociateCommonFiletypes=No,OperationDoesNotExistError=Abort,OverwriteTargetDirectory=No,installationErrorWithCancel=Cancel,stopProcessesForUpdates=Cancel"
            --verbose
            install ${packages}
        INPUT_FILE "${CMAKE_CURRENT_LIST_DIR}/empty-input.txt"
        OUTPUT_FILE "${private}/installer.log" ERROR_FILE "${private}/installer.log"
        RESULT_VARIABLE rc TIMEOUT 2400)
    set(ENV{HOME} "${saved_home}")
    set(ENV{USERPROFILE} "${saved_userprofile}")
    unset(ENV{QT_QPA_PLATFORM})
    # Restore TMPDIR: the private directory is deleted below, and later
    # dependency builds in this configure need a working temp directory.
    if(saved_tmpdir_defined)
        set(ENV{TMPDIR} "${saved_tmpdir}")
    else()
        unset(ENV{TMPDIR})
    endif()
    file(REMOVE_RECURSE "${private}/home")

    # Sanitized excerpt only; the raw log stays in the private directory.
    file(STRINGS "${private}/installer.log" lines)
    set(excerpt "")
    foreach(l IN LISTS lines)
        if(l MATCHES "(Error|error|Warning|warning|Installing|Extracting|Cannot install|virtual|license|obligation|Aborting|Cancel)")
            string(REGEX REPLACE "[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]+" "<email>" l "${l}")
            string(REGEX REPLACE "eyJ[A-Za-z0-9._-]+" "<token>" l "${l}")
            string(APPEND excerpt "${l}\n")
        endif()
    endforeach()
    file(WRITE "${HIKARI_EVIDENCE_DIR}/qt-installer-excerpt.log" "${excerpt}")
    # The raw log can name the account; only the sanitized excerpt survives.
    file(REMOVE_RECURSE "${private}")
    if(NOT rc STREQUAL "0")
        message(FATAL_ERROR "Official Qt installer failed (${rc}); see ${HIKARI_EVIDENCE_DIR}/qt-installer-excerpt.log")
    endif()

    # selected <= installed <= selected + conditional: the installer skips a
    # refused (virtual) request and still exits 0.
    if(NOT EXISTS "${target}/components.xml")
        message(FATAL_ERROR "Qt installer exited 0 but wrote no components.xml")
    endif()
    file(READ "${target}/components.xml" comps)
    string(REGEX MATCHALL "<Name>[^<]+</Name>" raw "${comps}")
    set(installed "")
    foreach(n IN LISTS raw)
        string(REGEX REPLACE "</?Name>" "" n "${n}")
        list(APPEND installed "${n}")
    endforeach()
    _hikari_json_list("${lock}" selected selected)
    _hikari_json_list("${lock}" conditional conditional)
    set(missing "")
    foreach(n IN LISTS selected)
        if(NOT n IN_LIST installed)
            list(APPEND missing "${n}")
        endif()
    endforeach()
    set(unknown "")
    foreach(n IN LISTS installed)
        if(NOT n IN_LIST selected AND NOT n IN_LIST conditional)
            list(APPEND unknown "${n}")
        endif()
    endforeach()
    list(JOIN installed "\n" installed_text)
    file(WRITE "${HIKARI_EVIDENCE_DIR}/qt-installed-components.txt" "${installed_text}\n")
    if(missing OR unknown)
        message(FATAL_ERROR "Qt closure mismatch; missing: ${missing}; outside the lock: ${unknown}")
    endif()
    file(WRITE "${stamp}" "${lock_digest}\n")
    set(HIKARI_QT_ROOT "${target}" PARENT_SCOPE)
endfunction()
