# Pinned vcpkg: an exact registry checkout plus the official, digest-verified
# tool executable. Supplying the executable means vcpkg's bootstrap scripts
# never run. Must complete before project() sets the toolchain.
include_guard(GLOBAL)

function(_hikari_git label)
    execute_process(COMMAND git -c credential.helper= ${ARGN}
        OUTPUT_VARIABLE out ERROR_VARIABLE err RESULT_VARIABLE rc TIMEOUT 1800)
    if(NOT rc STREQUAL "0")
        message(FATAL_ERROR "vcpkg ${label} failed (${rc}): ${err}")
    endif()
endfunction()

function(_hikari_git_output out_var)
    execute_process(COMMAND git ${ARGN} OUTPUT_VARIABLE out RESULT_VARIABLE rc
        OUTPUT_STRIP_TRAILING_WHITESPACE ERROR_QUIET TIMEOUT 60)
    if(NOT rc STREQUAL "0")
        set(out "")
    endif()
    set(${out_var} "${out}" PARENT_SCOPE)
endfunction()

function(hikari_provision_vcpkg platform)
    file(READ "${HIKARI_LOCK_DIR}/vcpkg.lock.json" lock)
    string(JSON repo GET "${lock}" repository)
    string(JSON commit GET "${lock}" commit)
    string(JSON tree GET "${lock}" tree)
    string(JSON release GET "${lock}" tool_release)
    string(JSON asset GET "${lock}" tools ${platform} asset)
    string(JSON tool_sha GET "${lock}" tools ${platform} sha256)
    string(JSON tool_bytes GET "${lock}" tools ${platform} bytes)
    find_program(HIKARI_GIT git REQUIRED)

    set(root "${HIKARI_SDK_DIR}/vcpkg")
    # Partial clone: commit/tree history now, historic port blobs on demand.
    if(NOT EXISTS "${root}/.git")
        file(MAKE_DIRECTORY "${root}")
        _hikari_git(init -C "${root}" init -q)
        _hikari_git(remote -C "${root}" remote add origin "${repo}")
        _hikari_git(promisor -C "${root}" config remote.origin.promisor true)
        _hikari_git(filter -C "${root}" config remote.origin.partialclonefilter blob:none)
        _hikari_git(fetch -C "${root}" fetch -q --filter=blob:none --no-tags origin "${commit}")
        _hikari_git(checkout -C "${root}" checkout -q --detach "${commit}")
    endif()
    _hikari_git_output(head -C "${root}" rev-parse HEAD)
    _hikari_git_output(head_tree -C "${root}" rev-parse "HEAD^{tree}")
    _hikari_git_output(dirty -C "${root}" status --porcelain --untracked-files=no)
    if(NOT head STREQUAL commit OR NOT head_tree STREQUAL tree OR NOT dirty STREQUAL "")
        message(FATAL_ERROR "vcpkg checkout at ${root} is not the locked, clean ${commit}; remove it to re-provision")
    endif()
    file(READ "${root}/scripts/vcpkg-tool-metadata.txt" metadata)
    if(NOT metadata MATCHES "VCPKG_TOOL_RELEASE_TAG=${release}([\r\n]|$)")
        message(FATAL_ERROR "vcpkg registry expects a different tool release than the locked ${release}")
    endif()

    if(platform STREQUAL "windows")
        set(tool "${root}/vcpkg.exe")
    else()
        set(tool "${root}/vcpkg")
    endif()
    set(ok FALSE)
    if(EXISTS "${tool}")
        file(SHA256 "${tool}" actual)
        if(actual STREQUAL tool_sha)
            set(ok TRUE)
        else()
            file(REMOVE "${tool}")
        endif()
    endif()
    if(NOT ok)
        file(DOWNLOAD "https://github.com/microsoft/vcpkg-tool/releases/download/${release}/${asset}"
            "${tool}" EXPECTED_HASH SHA256=${tool_sha} TLS_VERIFY ON
            TIMEOUT 300 INACTIVITY_TIMEOUT 30 STATUS st)
        list(GET st 0 rc)
        if(NOT rc EQUAL 0)
            file(REMOVE "${tool}")
            message(FATAL_ERROR "Official vcpkg tool acquisition failed: ${st}")
        endif()
    endif()
    file(SIZE "${tool}" actual_bytes)
    if(NOT actual_bytes EQUAL tool_bytes)
        message(FATAL_ERROR "vcpkg tool size ${actual_bytes} differs from the locked ${tool_bytes}")
    endif()
    if(NOT platform STREQUAL "windows")
        file(CHMOD "${tool}" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
    endif()

    set(ENV{VCPKG_DISABLE_METRICS} "1")
    set(ENV{VCPKG_ROOT} "${root}")
    set(HIKARI_VCPKG_ROOT "${root}" PARENT_SCOPE)
endfunction()
