#pragma once

// The content of the Y9 Matroska fixtures (hikari_mkv_fixture): the writer
// and the tests share it, so the tests know every byte the files hold.

#include <cstdint>
#include <string>
#include <utility>
#include <vector>

namespace mkvfixture {

struct Track {
    std::string codecId, codecPrivate, language, name;
};
struct Packet {
    std::int64_t start = 0, duration = 0; // milliseconds
    std::string data;
};
struct Attachment {
    std::string filename, mimetype, data;
};
struct File {
    double durationMs = 0; // the Segment Info Duration; 0: none
    std::vector<Track> tracks;
    std::vector<std::pair<int, Packet>> packets; // track index, packet, in file order
    std::vector<Attachment> attachments;
};

// Deterministic bytes standing in for a font (legacy never looks inside).
inline std::string fontBytes(int seed, std::size_t size)
{
    std::string out(size, '\0');
    std::uint32_t x = 2463534242u + std::uint32_t(seed) * 7919u;
    for (auto &c : out) {
        x ^= x << 13;
        x ^= x >> 17;
        x ^= x << 5;
        c = char(x & 0xFF);
    }
    return out;
}

inline const std::string kAssPrivate =
    "[Script Info]\r\n"
    "; Script generated by a muxer\r\n"
    "Title: Fixture\r\n"
    "ScriptType: v4.00+\r\n"
    "PlayResX: 1920\r\n"
    "PlayResY: 1080\r\n"
    "NoColonLine\r\n"
    "Title: Fixture again\r\n"
    "YCbCr Matrix: None\r\n"
    "\r\n"
    "[V4+ Styles]\r\n"
    "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, "
    "Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, "
    "MarginR, MarginV, Encoding\r\n"
    "Style: Default,Arial,48,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1\r\n"
    "Style: Sign,Times New Roman,40,&H0000FFFF,&H000000FF,&H00000000,&H80000000,-1,0,0,0,100,100,0,0,1,2,0,8,10,10,"
    "10,1\r\n"
    "Late: after the styles\r\n"
    "\n"
    "[Events]\n"
    "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n"
    "Comment: 0,0:00:00.00,0:00:00.00,Default,,0,0,0,,header comment\n";

inline const std::string kSsaPrivate =
    "[Script Info]\r\n"
    "ScriptType: v4.00\r\n"
    "\r\n"
    "[V4 Styles]\r\n"
    "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, TertiaryColour, BackColour, Bold, Italic, "
    "BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, AlphaLevel, Encoding\r\n"
    "Style: Default,Arial,20,16777215,65535,65535,-2147483640,-1,0,1,3,0,2,30,30,30,0,0\r\n";

// Track indices in `subs`: 0 ASS, 1 SSA, 2 SubRip, 3 plain text, 4 PGS,
// 5 WebVTT; attachments follow them as streams 6-14.
inline File subs()
{
    File f;
    f.durationMs = 7300000;
    f.tracks = {{"S_TEXT/ASS", kAssPrivate, "eng", "Signs"},
                {"S_TEXT/SSA", kSsaPrivate, "jpn", ""},
                {"S_TEXT/UTF8", "", "eng", "Full"},
                {"S_TEXT/ASCII", "", "", ""},
                {"S_HDMV/PGS", "", "eng", "Bitmap"},
                {"S_TEXT/WEBVTT", "", "fre", "Web"}};
    using P = Packet;
    f.packets = {
        {0, P{1234, 2000, "0,0,Default,,0,0,0,,Hello, world"}},
        {2, P{1001, 1499, "Line one\nLine two"}},
        {0, P{500, 1000, "1,2,Sign,Actor,10,20,30,fx,{\\pos(1,2)}Sign"}},
        {0, P{3725, 10, "2,,Default,,0,0,0,,no layer"}},
        {1, P{2000, 500, "0,Marked=0,Default,,0000,0000,0000,,SSA line"}},
        {0, P{7199996, 1, "3,0,Default,,0,0,0,,large"}},
        {0, P{4000, 994, "4,0,,Actor,0,0,0,,empty style"}},
        {0, P{4100, 100, "x"}},
        {0, P{4200, 100, "56"}},
        {0, P{4300, 100, "6,0,Default,,0,0,0,,\xff\xfe"}},
        {0, P{4400, 100, std::string("7,0,Default,,0,0,0,,before\0after", 31)}},
        {0, P{4500, 99, "8, 3,Default,,0,0,0,,spaced layer"}},
        {0, P{4600, 100, "9,12abc,Default,,0,0,0,,partial layer"}},
        {2, P{0, 0, "At zero"}},
        {2, P{3600000 + 61001, 2999, "a\r\nb"}},
        {2, P{5000, 1000, "\xc5\xbc\xc3\xb3\xc5\x82w"}},
        {3, P{6000, 1500, "plain text"}},
        {5, P{7000, 1000, "web"}},
    };
    f.attachments = {
        {"Fixture Sans.ttf", "font/ttf", fontBytes(1, 70000)},
        {"dir/sub\\Nested.otf", "application/vnd.ms-opentype", fontBytes(2, 5000)},
        {"", "font/otf", fontBytes(3, 4000)},
        {"..", "application/x-truetype-font", fontBytes(4, 3000)},
        {"Za\xc5\xbc\xc3\xb3\xc5\x82\xc4\x87.ttf", "font/ttf", fontBytes(5, 2000)},
        {"Caf\xe9.ttf", "font/ttf", fontBytes(6, 1000)},
        {"cover.png", "image/png", fontBytes(7, 500)},
        {"dup.ttf", "font/ttf", fontBytes(8, 1500)},
        {"dup.ttf", "application/x-truetype-font", fontBytes(9, 1600)},
    };
    return f;
}

inline File oneSub()
{
    File f;
    f.durationMs = 6000;
    f.tracks = {{"S_HDMV/PGS", "", "eng", ""}, {"S_TEXT/UTF8", "", "pol", "Polski"}};
    f.packets = {{1, Packet{1000, 2000, "Jeden"}}, {1, Packet{4000, 1000, "Dwa"}}};
    return f;
}

inline File noSubs()
{
    File f;
    f.tracks = {{"S_HDMV/PGS", "", "eng", ""}, {"S_TEXT/WEBVTT", "", "eng", ""}};
    f.packets = {{1, Packet{1000, 1000, "web"}}};
    return f;
}

// The "mkvextract" media fixture (hikari_media_fixture): a video with an
// ASS track (0) and a SubRip track (1), and two font attachments.
inline const std::string kMkvExtractHeader =
    "[Script Info]\r\n"
    "ScriptType: v4.00+\r\n"
    "PlayResX: 320\r\n"
    "PlayResY: 240\r\n"
    "\r\n"
    "[V4+ Styles]\r\n"
    "Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, "
    "Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, "
    "MarginR, MarginV, Encoding\r\n"
    "Style: Default,Arial,20,&H00FFFFFF,&H000000FF,&H00000000,&H00000000,0,0,0,0,100,100,0,0,1,2,2,2,10,10,10,1\r\n"
    "\r\n"
    "[Events]\r\n"
    "Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\r\n";

inline std::vector<std::pair<int, Packet>> mkvExtractPackets()
{
    return {{0, Packet{200, 400, "0,0,Default,,0,0,0,,Sign one"}},
            {1, Packet{500, 1000, "Pierwsza"}},
            {0, Packet{1234, 500, "1,1,Default,Actor,0,0,0,,Sign two"}}};
}

inline std::vector<Attachment> mkvExtractFonts()
{
    return {{"Extract Sans.ttf", "font/ttf", fontBytes(11, 3000)},
            {"fonts/Extract Serif.otf", "application/vnd.ms-opentype", fontBytes(12, 2000)}};
}

} // namespace mkvfixture
