#!/usr/bin/env python3
"""Copies named definitions out of a legacy source file, unchanged.

Usage: extract_functions.py <source> <output> <signature>...

Each signature is the start of a definition as it is written in the source
(for example "bool RendererVideo::UpdateRects(bool changeZoom)" or
"class FloatRect"); the definition runs from there to the brace that closes
its body (and a following ';' for a class). Every signature must match
exactly once. The output holds the definitions in the order given, each after
a #line directive naming its place in the source, so compiler messages and
the probe's citations point at the legacy file.
"""
import sys


def body_end(text, start):
    depth = 0
    i = text.index("{", start)
    while i < len(text):
        c = text[i]
        if c == "/" and text.startswith("//", i):
            i = text.index("\n", i)
            continue
        if c == "/" and text.startswith("/*", i):
            i = text.index("*/", i) + 2
            continue
        if c in "\"'":
            j = i + 1
            while text[j] != c:
                j += 2 if text[j] == "\\" else 1
            i = j + 1
            continue
        if c == "{":
            depth += 1
        elif c == "}":
            depth -= 1
            if depth == 0:
                return i + 1
        i += 1
    raise SystemExit("unbalanced braces")


def main():
    source, output, signatures = sys.argv[1], sys.argv[2], sys.argv[3:]
    with open(source, encoding="utf-8-sig") as f:
        text = f.read().replace("\r\n", "\n")
    parts = []
    for signature in signatures:
        first = text.find(signature)
        if first < 0 or text.find(signature, first + 1) >= 0:
            raise SystemExit(f"{source}: '{signature}' must occur exactly once")
        end = body_end(text, first)
        if signature.startswith(("class ", "struct ")) and text[end:end + 1] == ";":
            end += 1
        line = text.count("\n", 0, first) + 1
        parts.append(f'#line {line} "{source}"\n{text[first:end]}\n')
    with open(output, "w", encoding="utf-8") as f:
        f.write("// Generated by extract_functions.py: legacy definitions, unchanged.\n")
        f.write("".join(parts))


if __name__ == "__main__":
    main()
