# Package manifest of a helper executable (I6, M50-helper): its static vcpkg
# closure with reviewed licences and copyright files, and its dynamic
# dependencies, which must all be operating-system libraries. Script mode:
#
#   cmake -DHELPER=<exe> -DNAME=<component> -DROOTS=<pkg;...> -DSTATUS=<vcpkg status>
#         -DINSTALLED=<vcpkg_installed/<triplet>> -DTRIPLET=<triplet> -DLICENCES=<json>
#         -DOUT=<manifest.json> -P HelperManifest.cmake
cmake_minimum_required(VERSION 3.28)
foreach(var HELPER NAME ROOTS STATUS INSTALLED TRIPLET LICENCES OUT)
    if(NOT DEFINED ${var})
        message(FATAL_ERROR "HelperManifest: ${var} is required")
    endif()
endforeach()
set(problems "")

# Installed packages of the target triplet: version and same-triplet dependencies.
file(READ "${STATUS}" status)
string(REPLACE "\r" "" status "${status}")
string(REPLACE ";" "," status "${status}")
string(REGEX REPLACE "\n\n+" ";" paragraphs "${status}")
foreach(p IN LISTS paragraphs)
    if(NOT p MATCHES "Package: ([^\n]+)")
        continue()
    endif()
    set(pkg "${CMAKE_MATCH_1}")
    if(NOT p MATCHES "Architecture: ${TRIPLET}\n" OR NOT p MATCHES "Status: install ok installed")
        continue()
    endif()
    if(p MATCHES "Feature: ([^\n]+)")
        list(APPEND features_${pkg} "${CMAKE_MATCH_1}")
        continue()
    endif()
    string(REGEX MATCH "Version: ([^\n]+)" _ "${p}")
    set(version_${pkg} "${CMAKE_MATCH_1}")
    if(p MATCHES "Port-Version: ([^\n]+)")
        string(APPEND version_${pkg} "#${CMAKE_MATCH_1}")
    endif()
    set(deps_${pkg} "")
    if(p MATCHES "Depends: ([^\n]+)")
        string(REPLACE "," ";" deps "${CMAKE_MATCH_1}")
        foreach(d IN LISTS deps)
            string(STRIP "${d}" d)
            string(REGEX REPLACE "\\[.*\\]" "" d "${d}")
            if(NOT d MATCHES ":") # host tools carry their triplet; they are not linked
                list(APPEND deps_${pkg} "${d}")
            endif()
        endforeach()
    endif()
    list(APPEND installed "${pkg}")
endforeach()

# Static closure from the roots.
set(closure "")
set(queue ${ROOTS})
while(queue)
    list(POP_FRONT queue pkg)
    if(pkg IN_LIST closure)
        continue()
    endif()
    if(NOT pkg IN_LIST installed)
        list(APPEND problems "package ${pkg} is not installed for ${TRIPLET}")
        continue()
    endif()
    list(APPEND closure "${pkg}")
    list(APPEND queue ${deps_${pkg}})
endwhile()
list(SORT closure)

file(READ "${LICENCES}" licences)
string(JSON reviewed_count LENGTH "${licences}" packages)
set(reviewed "")
math(EXPR last "${reviewed_count} - 1")
foreach(i RANGE ${last})
    string(JSON name MEMBER "${licences}" packages ${i})
    list(APPEND reviewed "${name}")
endforeach()

set(static_json "")
foreach(pkg IN LISTS closure)
    string(JSON licence ERROR_VARIABLE missing GET "${licences}" packages ${pkg} license)
    if(missing)
        list(APPEND problems "no reviewed licence for ${pkg}")
        set(licence "")
    endif()
    set(copyright "${INSTALLED}/share/${pkg}/copyright")
    set(copyright_sha "")
    if(EXISTS "${copyright}")
        file(SHA256 "${copyright}" copyright_sha)
    else()
        list(APPEND problems "no copyright file for ${pkg}")
    endif()
    set(feature_json "")
    if(features_${pkg})
        list(SORT features_${pkg})
        list(JOIN features_${pkg} "\", \"" joined)
        set(feature_json "\"${joined}\"")
    endif()
    string(APPEND static_json "    {\"package\": \"${pkg}\", \"version\": \"${version_${pkg}}\", \"features\": [${feature_json}], \"license\": \"${licence}\", \"copyright\": \"share/${pkg}/copyright\", \"copyrightSha256\": \"${copyright_sha}\"},\n")
endforeach()
foreach(name IN LISTS reviewed)
    if(NOT name IN_LIST closure)
        list(APPEND problems "reviewed licence for ${name}, which is no longer linked")
    endif()
endforeach()
string(REGEX REPLACE ",\n$" "\n" static_json "${static_json}")

# Dynamic dependencies: operating-system libraries, plus the compiler runtime,
# which is listed apart because shipping it is a packaging decision. Anything
# else would have to be shipped and licensed, and fails the manifest.
set(os_libs "")
set(runtime_libs "")
if(CMAKE_HOST_WIN32)
    # Direct imports only: walking into system DLLs finds their delay-loads.
    find_program(DUMPBIN dumpbin REQUIRED)
    execute_process(COMMAND "${DUMPBIN}" /nologo /dependents "${HELPER}" OUTPUT_VARIABLE imports
        RESULT_VARIABLE rc)
    if(NOT rc EQUAL 0)
        list(APPEND problems "dumpbin failed on ${HELPER}")
    endif()
    string(REGEX MATCHALL "[A-Za-z0-9_.-]+\\.[Dd][Ll][Ll]" dlls "${imports}")
    list(REMOVE_DUPLICATES dlls)
    foreach(dll IN LISTS dlls)
        string(TOLOWER "${dll}" lower)
        if(lower MATCHES "^(msvcp|vcruntime|concrt|vccorlib)[0-9_]*\\.dll$")
            list(APPEND runtime_libs "${dll}") # the Visual C++ Redistributable
        elseif(lower MATCHES "^api-ms-win-crt-" OR EXISTS "$ENV{SystemRoot}/System32/${dll}")
            list(APPEND os_libs "${dll}") # the UCRT ships with Windows 10 and later
        else()
            list(APPEND problems "dynamic dependency ${dll} is not an operating-system library")
        endif()
    endforeach()
else()
    set(CMAKE_GET_RUNTIME_DEPENDENCIES_PLATFORM "linux+elf")
    file(GET_RUNTIME_DEPENDENCIES
        EXECUTABLES "${HELPER}"
        RESOLVED_DEPENDENCIES_VAR resolved
        UNRESOLVED_DEPENDENCIES_VAR unresolved)
    foreach(dep IN LISTS resolved)
        get_filename_component(file "${dep}" NAME)
        if(NOT dep MATCHES "^/(usr/)?lib(64|32)?/")
            list(APPEND problems "dynamic dependency ${dep} is not an operating-system library")
        elseif(file MATCHES "^(libstdc\\+\\+|libgcc_s|libatomic)\\.so")
            list(APPEND runtime_libs "${file}")
        else()
            list(APPEND os_libs "${file}")
        endif()
    endforeach()
    foreach(dep IN LISTS unresolved)
        list(APPEND problems "unresolved dynamic dependency ${dep}")
    endforeach()
endif()
function(json_strings out)
    set(text "")
    foreach(item IN LISTS ARGN)
        string(APPEND text "    \"${item}\",\n")
    endforeach()
    string(REGEX REPLACE ",\n$" "\n" text "${text}")
    set(${out} "${text}" PARENT_SCOPE)
endfunction()
list(SORT os_libs)
list(SORT runtime_libs)
json_strings(os_json ${os_libs})
json_strings(runtime_json ${runtime_libs})

file(SHA256 "${HELPER}" helper_sha)
get_filename_component(helper_file "${HELPER}" NAME)
file(WRITE "${OUT}" "{\n  \"component\": \"${NAME}\",\n  \"triplet\": \"${TRIPLET}\",\n  \"executable\": {\"file\": \"${helper_file}\", \"sha256\": \"${helper_sha}\"},\n  \"static\": [\n${static_json}  ],\n  \"operatingSystemLibraries\": [\n${os_json}  ],\n  \"compilerRuntime\": [\n${runtime_json}  ]\n}\n")
if(problems)
    list(JOIN problems "\n  " text)
    message(FATAL_ERROR "FAIL: ${NAME} manifest is incomplete:\n  ${text}")
endif()
list(JOIN closure ", " closure_text)
message(STATUS "PASS ${NAME} manifest: ${closure_text}; ${OUT}")
