# Stage 1-2: acquire locked objects into a local repository mirror. No
# credentials. Changed upstream bytes fail the lock; they are never adopted.
include("${CMAKE_CURRENT_LIST_DIR}/common.cmake")
option(HIKARI_QT_VERIFY_ONLY "Verify the existing mirror without acquiring anything" OFF)
qf_status("ACQUIRE: started; no Qt installation yet")

string(JSON obj_bytes GET "${qf_lock}" declared_bytes objects)
string(JSON inst_bytes GET "${qf_lock}" installer length)
math(EXPR declared "${obj_bytes} + ${inst_bytes}")
if(declared GREATER qf_budget_bytes)
    message(FATAL_ERROR "Declared acquisition ${declared} exceeds the ${qf_budget_bytes}-byte stop bound")
endif()

qf_mirror_entries(entries)
string(JSON inst_url GET "${qf_lock}" installer url)
string(JSON inst_sha GET "${qf_lock}" installer sha256)
string(JSON inst_declared GET "${qf_lock}" installer declared_sha256)
if(NOT inst_sha STREQUAL inst_declared)
    message(FATAL_ERROR "Locked installer digest differs from the plan's declared SHA-256")
endif()
list(APPEND entries "@installer|${inst_url}|${inst_bytes}|${inst_sha}")

set(tsv "path\tlength\tsha256\taction\n")
set(fetched 0)
set(expected_paths "")
foreach(e IN LISTS entries)
    string(REPLACE "|" ";" f "${e}")
    list(GET f 0 path)
    list(GET f 1 url)
    list(GET f 2 len)
    list(GET f 3 sha)
    if(path STREQUAL "@installer")
        set(dest "${qf_installer}")
    else()
        set(dest "${qf_mirror}/${path}")
        list(APPEND expected_paths "${dest}")
    endif()
    qf_verify_file("${dest}" ${len} ${sha} ok)
    if(ok)
        set(action cached)
    elseif(HIKARI_QT_VERIFY_ONLY)
        file(APPEND "${qf_evidence}/verify-rejections.tsv" "${path}\t${len}\t${sha}\n")
        message(FATAL_ERROR "Mirror object missing or changed: ${path}")
    else()
        set(action downloaded)
        if(EXISTS "${dest}")
            set(action refetched-after-mismatch)
            file(REMOVE "${dest}")
        endif()
        math(EXPR fetched "${fetched} + ${len}")
        if(fetched GREATER qf_budget_bytes)
            message(FATAL_ERROR "Acquisition exceeded the stop bound at ${path}")
        endif()
        file(DOWNLOAD "${url}" "${dest}" EXPECTED_HASH SHA256=${sha} TLS_VERIFY ON
            TIMEOUT 900 INACTIVITY_TIMEOUT 60 STATUS st)
        list(GET st 0 rc)
        qf_verify_file("${dest}" ${len} ${sha} ok)
        if(NOT rc EQUAL 0 OR NOT ok)
            file(REMOVE "${dest}")
            message(FATAL_ERROR "Locked object rejected: ${path} (${st})")
        endif()
    endif()
    string(APPEND tsv "${path}\t${len}\t${sha}\t${action}\n")
endforeach()
file(CHMOD "${qf_installer}" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE)

# The mirror holds locked objects only; anything else fails the allowlist.
file(GLOB_RECURSE present LIST_DIRECTORIES false "${qf_mirror}/*")
list(REMOVE_ITEM present ${expected_paths})
if(present)
    message(FATAL_ERROR "Unlocked files in mirror: ${present}")
endif()

file(WRITE "${qf_evidence}/acquired.tsv" "${tsv}")
file(APPEND "${qf_evidence}/acquire-summary.txt"
    "declared_bytes=${declared}\ntransferred_bytes=${fetched}\nverify_only=${HIKARI_QT_VERIFY_ONLY}\n")
qf_status("ACQUIRED: mirror and installer match the lock; no Qt installation yet")
