cmake_minimum_required(VERSION 3.28)
get_filename_component(qf_dir "${CMAKE_CURRENT_LIST_DIR}/.." ABSOLUTE)
set(qf_work "${qf_dir}/_work")
set(qf_mirror "${qf_work}/mirror")
set(qf_evidence "${qf_dir}/_evidence")
set(qf_lock_file "${qf_dir}/lock/qt-linux.lock.json")
set(qf_installer "${qf_work}/installer/qt-online-installer-linux-x64-4.11.0.run")
set(qf_budget_bytes 805306368) # 768 MiB acquisition stop bound
set(CMAKE_TLS_VERIFY ON)
file(MAKE_DIRECTORY "${qf_work}" "${qf_evidence}")
file(READ "${qf_lock_file}" qf_lock)

# The lock is the only authority: reject an incomplete or problem-bearing one.
string(JSON qf_complete GET "${qf_lock}" complete)
string(JSON qf_problems LENGTH "${qf_lock}" problems)
if(NOT qf_complete OR NOT qf_problems EQUAL 0)
    message(FATAL_ERROR "Lock incomplete or has recorded problems; regenerate and review it first")
endif()
string(JSON qf_base GET "${qf_lock}" base)

function(qf_status text)
    file(WRITE "${qf_evidence}/status.txt" "${text}\n")
    message(STATUS "${text}")
endfunction()

# Emit "path;url;length;sha256" entries for every mirror object, roots first.
function(qf_mirror_entries out_var)
    set(entries "")
    string(JSON n LENGTH "${qf_lock}" roots)
    math(EXPR last "${n} - 1")
    foreach(i RANGE ${last})
        string(JSON url GET "${qf_lock}" roots ${i} updates_xml url)
        string(JSON len GET "${qf_lock}" roots ${i} updates_xml length)
        string(JSON sha GET "${qf_lock}" roots ${i} updates_xml sha256)
        string(LENGTH "${qf_base}" bl)
        string(SUBSTRING "${url}" ${bl} -1 path)
        list(APPEND entries "${path}|${url}|${len}|${sha}")
    endforeach()
    string(JSON n LENGTH "${qf_lock}" objects)
    math(EXPR last "${n} - 1")
    foreach(i RANGE ${last})
        foreach(k path url length sha256)
            string(JSON ${k} GET "${qf_lock}" objects ${i} ${k})
        endforeach()
        list(APPEND entries "${path}|${url}|${length}|${sha256}")
    endforeach()
    set(${out_var} "${entries}" PARENT_SCOPE)
endfunction()

function(qf_verify_file file length sha out_ok)
    set(ok FALSE)
    if(EXISTS "${file}")
        file(SIZE "${file}" actual_len)
        if(actual_len EQUAL length)
            file(SHA256 "${file}" actual_sha)
            if(actual_sha STREQUAL sha)
                set(ok TRUE)
            endif()
        endif()
    endif()
    set(${out_ok} ${ok} PARENT_SCOPE)
endfunction()
