include("${CMAKE_CURRENT_LIST_DIR}/common.cmake")
if(EXISTS "${evidence}/process-result.txt")
    file(READ "${evidence}/process-result.txt" process_result)
else()
    set(process_result "missing")
endif()
if(EXISTS "${evidence}/resource-stop.txt" OR NOT process_result MATCHES "driver_exit=0[\r\n]+resource_stop=0")
    file(WRITE "${evidence}/status.txt" "FAILED_OR_INCOMPLETE: driver exit/limits not clean; no Linux source-slice pass\n")
endif()
file(GLOB_RECURSE logs LIST_DIRECTORIES false
    "${vcpkg_root}/buildtrees/*.log" "${overlay_dir}/out/linux-overlay/*.log"
    "${overlay_dir}/out/linux-overlay/vcpkg_installed/vcpkg/status")
foreach(path IN LISTS logs)
    file(RELATIVE_PATH relative "${overlay_dir}" "${path}")
    get_filename_component(parent "${evidence}/build-logs/${relative}" DIRECTORY)
    file(MAKE_DIRECTORY "${parent}")
    file(COPY_FILE "${path}" "${evidence}/build-logs/${relative}")
endforeach()
file(GLOB_RECURSE archives LIST_DIRECTORIES false "${work}/downloads/*")
file(WRITE "${evidence}/acquired-file-sha256.tsv" "sha256\tbytes\tpath\n")
foreach(path IN LISTS archives)
    if(NOT path MATCHES "/(git-trees|tools)/")
        file(SHA256 "${path}" hash)
        file(SIZE "${path}" bytes)
        file(RELATIVE_PATH relative "${work}/downloads" "${path}")
        file(APPEND "${evidence}/acquired-file-sha256.tsv" "${hash}\t${bytes}\t${relative}\n")
    endif()
endforeach()
# No binary, media fixture, cache, archive or full environment enters artifacts.
file(GLOB inputs LIST_DIRECTORIES false "${ci_dir}/*.cmake")
list(APPEND inputs "${ci_dir}/CMakeLists.txt" "${ci_dir}/CMakePresets.json"
    "${overlay_dir}/CMakeLists.txt" "${overlay_dir}/CMakePresets.json" "${overlay_dir}/probe.cpp"
    "${overlay_dir}/vcpkg.json" "${overlay_dir}/vcpkg-configuration.json")
file(GLOB_RECURSE port_inputs LIST_DIRECTORIES false "${overlay_dir}/ports/*" "${overlay_dir}/triplets/*")
list(APPEND inputs ${port_inputs})
file(WRITE "${evidence}/recipe-sha256.tsv" "sha256\tpath\n")
foreach(path IN LISTS inputs)
    if(NOT path MATCHES "/(_work|_evidence)/")
        file(SHA256 "${path}" hash)
        file(RELATIVE_PATH relative "${overlay_dir}" "${path}")
        file(APPEND "${evidence}/recipe-sha256.tsv" "${hash}\t${relative}\n")
    endif()
endforeach()
if(NOT EXISTS "${evidence}/status.txt")
    file(WRITE "${evidence}/status.txt" "NOT_STARTED_OR_EARLY_FAILURE: no source-build pass\n")
endif()
