cmake_minimum_required(VERSION 3.28)
set(ci_dir "${CMAKE_CURRENT_LIST_DIR}")
get_filename_component(overlay_dir "${ci_dir}/.." ABSOLUTE)
set(work "${ci_dir}/_work")
set(evidence "${ci_dir}/_evidence")
set(vcpkg_root "${work}/vcpkg")
file(MAKE_DIRECTORY "${work}" "${evidence}")
set(CMAKE_TLS_VERIFY ON)
file(READ "${overlay_dir}/inputs.lock.json" lock)
string(JSON registry_commit GET "${lock}" vcpkg commit_and_builtin_baseline)
string(JSON tool_release GET "${lock}" vcpkg required_tool_release_from_registry_metadata)
string(JSON tool_sha256 GET "${lock}" vcpkg linux_glibc_executable_sha256)
set(registry_tree "7312bd1d162dc2b9a2795fb6c9d67e7f364f47c4")
if(NOT registry_commit STREQUAL "ee6a47dac031930715bea2e6dfb9ad60caaa5d83"
   OR NOT tool_release STREQUAL "2026-07-27"
   OR NOT tool_sha256 STREQUAL "7e97ef6bcd58f74d079f40d086b801a0222c5d15e4ea0d8d507a538033493d04")
    message(FATAL_ERROR "Overlay input changed; review this bounded CI acquisition plan first")
endif()
set(ENV{VCPKG_ROOT} "${vcpkg_root}")
set(ENV{HIKARI_PROTOTYPE_VCPKG_ROOT} "${vcpkg_root}")
set(ENV{VCPKG_DOWNLOADS} "${work}/downloads")
set(ENV{VCPKG_DEFAULT_BINARY_CACHE} "${work}/binary-cache")
set(ENV{VCPKG_BINARY_SOURCES} "clear")
set(ENV{VCPKG_MAX_CONCURRENCY} "2")
set(ENV{VCPKG_DISABLE_METRICS} "1")
set(ENV{XDG_CACHE_HOME} "${work}/cache")
set(ENV{GIT_TERMINAL_PROMPT} "0")
file(MAKE_DIRECTORY "$ENV{VCPKG_DOWNLOADS}" "$ENV{VCPKG_DEFAULT_BINARY_CACHE}" "$ENV{XDG_CACHE_HOME}")

function(log_command name)
    message(STATUS "${name}; full scoped log: ${evidence}/${name}.log")
    execute_process(COMMAND ${ARGN} WORKING_DIRECTORY "${overlay_dir}"
        OUTPUT_FILE "${evidence}/${name}.log" ERROR_FILE "${evidence}/${name}.log"
        RESULT_VARIABLE result TIMEOUT 2800)
    file(APPEND "${evidence}/commands.tsv" "${name}\texit=${result}\n")
    if(NOT result STREQUAL "0")
        message(FATAL_ERROR "${name} failed: ${result}; retain logs, no qualification pass")
    endif()
endfunction()

function(require_output label expected)
    execute_process(COMMAND ${ARGN} OUTPUT_VARIABLE actual ERROR_VARIABLE error
        OUTPUT_STRIP_TRAILING_WHITESPACE RESULT_VARIABLE result TIMEOUT 60)
    if(NOT result STREQUAL "0" OR NOT actual STREQUAL expected)
        message(FATAL_ERROR "${label} identity mismatch: '${actual}' (exit ${result})")
    endif()
    file(APPEND "${evidence}/identities.txt" "${label}=${actual}\n")
endfunction()
