include("${CMAKE_CURRENT_LIST_DIR}/common.cmake")
cmake_host_system_information(RESULT host_arch QUERY OS_PLATFORM)
if(NOT CMAKE_HOST_SYSTEM_NAME STREQUAL "Linux" OR NOT host_arch MATCHES "^(x86_64|AMD64)$")
    message(FATAL_ERROR "This source-build driver is Linux x64 only")
endif()
foreach(tool git ninja gcc g++ make pkg-config autoconf automake nasm python3 curl tar unzip zip)
    find_program(found_${tool} NAMES "${tool}" REQUIRED)
endforeach()
file(WRITE "${evidence}/status.txt" "PROVISIONING: no source-build pass yet\n")
file(WRITE "${evidence}/identities.txt" "registry_expected=${registry_commit}\ntool_expected=${tool_sha256}\n")
file(COPY "${overlay_dir}/inputs.lock.json" "${overlay_dir}/dependency-plan.json" DESTINATION "${evidence}")
# No bootstrap shell script: CMake acquires the official executable explicitly.
# Partial clone retains commit/tree history; historic versioned port blobs are
# fetched on demand. Git transfers are covered by the CI receive/disk watchdog.
if(NOT EXISTS "${vcpkg_root}/.git")
    log_command(registry-init git init "${vcpkg_root}")
    log_command(registry-origin git -C "${vcpkg_root}" remote add origin https://github.com/microsoft/vcpkg.git)
    log_command(registry-promisor git -C "${vcpkg_root}" config remote.origin.promisor true)
    log_command(registry-filter git -C "${vcpkg_root}" config remote.origin.partialclonefilter blob:none)
    log_command(registry-fetch git -c credential.helper= -C "${vcpkg_root}" fetch --filter=blob:none --no-tags origin "${registry_commit}")
    log_command(registry-checkout git -c credential.helper= -C "${vcpkg_root}" checkout --detach "${registry_commit}")
endif()
require_output(registry_commit "${registry_commit}" git -C "${vcpkg_root}" rev-parse HEAD)
require_output(registry_tree "${registry_tree}" git -C "${vcpkg_root}" rev-parse "HEAD^{tree}")
log_command(registry-fsck git -C "${vcpkg_root}" fsck --connectivity-only --no-dangling)
file(READ "${vcpkg_root}/scripts/vcpkg-tool-metadata.txt" tool_metadata)
if(NOT tool_metadata MATCHES "VCPKG_TOOL_RELEASE_TAG=${tool_release}([\r\n]|$)")
    message(FATAL_ERROR "Registry/tool release mismatch")
endif()
string(REGEX MATCH "VCPKG_GLIBC_SHA=([0-9a-f]+)" matched "${tool_metadata}")
set(tool_sha512 "${CMAKE_MATCH_1}")
string(LENGTH "${tool_sha512}" hash_length)
if(NOT hash_length EQUAL 128)
    message(FATAL_ERROR "Missing official Linux tool SHA-512")
endif()
set(tool_path "${vcpkg_root}/vcpkg")
if(NOT EXISTS "${tool_path}")
    file(DOWNLOAD "https://github.com/microsoft/vcpkg-tool/releases/download/${tool_release}/vcpkg-glibc"
        "${tool_path}" EXPECTED_HASH "SHA256=${tool_sha256}" TLS_VERIFY ON
        TIMEOUT 180 INACTIVITY_TIMEOUT 30 STATUS download_status)
    list(GET download_status 0 download_result)
    if(NOT download_result EQUAL 0)
        message(FATAL_ERROR "Official vcpkg tool acquisition failed: ${download_status}")
    endif()
endif()
file(SHA256 "${tool_path}" actual256)
file(SHA512 "${tool_path}" actual512)
if(NOT actual256 STREQUAL tool_sha256 OR NOT actual512 STREQUAL tool_sha512)
    message(FATAL_ERROR "Official executable digest mismatch")
endif()
file(CHMOD "${tool_path}" PERMISSIONS OWNER_READ OWNER_WRITE OWNER_EXECUTE GROUP_READ GROUP_EXECUTE WORLD_READ WORLD_EXECUTE)
file(APPEND "${evidence}/identities.txt" "tool_sha256=${actual256}\ntool_sha512=${actual512}\n")
file(COPY "${vcpkg_root}/scripts/vcpkg-tool-metadata.txt" DESTINATION "${evidence}")
log_command(vcpkg-version "${tool_path}" version)
# The plan is evidence, not a build. It is retained even if the following source
# workflow fails. Host triplet is the native default x64-linux; target is owned.
log_command(resolved-plan "${tool_path}" install --dry-run --triplet=x64-hikari-linux-release
    "--overlay-triplets=${overlay_dir}/triplets" "--overlay-ports=${overlay_dir}/ports"
    "--x-manifest-root=${overlay_dir}" "--x-install-root=${overlay_dir}/out/linux-overlay/vcpkg_installed")
file(WRITE "${evidence}/status.txt" "PROVISIONED_AND_PLAN_CAPTURED: source build not yet passed\n")
