// Generated from HikariSub/ConfigConverter.cpp (ConfigConverter::CreateTable)
// and HikariSub/config.h (COLOR) at 20d647c4; settings_import_tests compares
// them with those sources and the migration worksheet.
#include "hikari/application/settings_import.h"

namespace hikari::application::settings_import {

std::span<const ConfigAlias> configAliases()
{
    static constexpr ConfigAlias table[] = {
        {"AudioAutoCommit", "AUDIO_AUTO_COMMIT", ""},
        {"AudioAutoFocus", "AUDIO_AUTO_FOCUS", ""},
        {"AudioAutoScroll", "AUDIO_AUTO_SCROLL", ""},
        {"AudioBoxHeight", "AUDIO_BOX_HEIGHT", ""},
        {"AudioDelay", "AUDIO_DELAY", ""},
        {"AudioDrawKeyframes", "AUDIO_DRAW_KEYFRAMES", ""},
        {"AudioDrawSecondaryLines", "AUDIO_DRAW_SECONDARY_LINES", ""},
        {"AudioDrawSelectionBackground", "AUDIO_DRAW_SELECTION_BACKGROUND", ""},
        {"AudioDrawTimeCursor", "AUDIO_DRAW_TIME_CURSOR", ""},
        {"AudioDrawVideoPosition", "AUDIO_DRAW_VIDEO_POSITION", ""},
        {"AudioGrabTimesOnSelect", "AUDIO_GRAB_TIMES_ON_SELECT", ""},
        {"AudioHorizontalZoom", "AUDIO_HORIZONTAL_ZOOM", ""},
        {"AudioInactiveLinesDisplayMode", "AUDIO_INACTIVE_LINES_DISPLAY_MODE", ""},
        {"AudioKaraoke", "AUDIO_KARAOKE", ""},
        {"AudioKaraokeMoveOnClick", "AUDIO_KARAOKE_MOVE_ON_CLICK", ""},
        {"AudioKaraokeSplitMode", "AUDIO_KARAOKE_SPLIT_MODE", ""},
        {"AudioLeadIn", "AUDIO_LEAD_IN_VALUE", ""},
        {"AudioLeadOut", "AUDIO_LEAD_OUT_VALUE", ""},
        {"AudioLineBoundariesThickness", "AUDIO_LINE_BOUNDARIES_THICKNESS", ""},
        {"AudioLink", "AUDIO_LINK", ""},
        {"AudioLockScrollOnCursor", "AUDIO_LOCK_SCROLL_ON_CURSOR", ""},
        {"AudioMarkPlayTime", "AUDIO_MARK_PLAY_TIME", ""},
        {"AudioMergeEveryNWithSyllable", "AUDIO_MERGE_EVERY_N_WITH_SYLLABLE", ""},
        {"AudioNextLineOnCommit", "AUDIO_NEXT_LINE_ON_COMMIT", ""},
        {"AudioRAMCache", "AUDIO_RAM_CACHE", ""},
        {"AudioSnapToKeyframes", "AUDIO_SNAP_TO_KEYFRAMES", ""},
        {"AudioSnapToOtherLines", "AUDIO_SNAP_TO_OTHER_LINES", ""},
        {"AudioSpectrumOn", "AUDIO_SPECTRUM_ON", ""},
        {"AudioSpectrumNonLinearOn", "AUDIO_SPECTRUM_NON_LINEAR_ON", ""},
        {"AudioStartDragSensitivity", "AUDIO_START_DRAG_SENSITIVITY", ""},
        {"AudioVerticalZoom", "AUDIO_VERTICAL_ZOOM", ""},
        {"AudioVolume", "AUDIO_VOLUME", ""},
        {"AudioWheelDefaultToZoom", "AUDIO_WHEEL_DEFAULT_TO_ZOOM", ""},
        {"AcceptedAudioStream", "ACCEPTED_AUDIO_STREAM", ""},
        {"ASSPropertiesTitle", "ASS_PROPERTIES_TITLE", ""},
        {"ASSPropertiesScript", "ASS_PROPERTIES_SCRIPT", ""},
        {"ASSPropertiesTranslation", "ASS_PROPERTIES_TRANSLATION", ""},
        {"ASSPropertiesEditing", "ASS_PROPERTIES_EDITING", ""},
        {"ASSPropertiesTiming", "ASS_PROPERTIES_TIMING", ""},
        {"ASSPropertiesUpdate", "ASS_PROPERTIES_UPDATE", ""},
        {"ASSPropertiesTitleOn", "ASS_PROPERTIES_TITLE_ON", ""},
        {"ASSPropertiesScriptOn", "ASS_PROPERTIES_SCRIPT_ON", ""},
        {"ASSPropertiesTranslationOn", "ASS_PROPERTIES_TRANSLATION_ON", ""},
        {"ASSPropertiesEditingOn", "ASS_PROPERTIES_EDITING_ON", ""},
        {"ASSPropertiesTimingOn", "ASS_PROPERTIES_TIMING_ON", ""},
        {"ASSPropertiesUpdateOn", "ASS_PROPERTIES_UPDATE_ON", ""},
        {"ASSPropertiesAskForChange", "ASS_PROPERTIES_ASK_FOR_CHANGE", ""},
        {"AudioRecent", "AUDIO_RECENT_FILES", "|"},
        {"AutomationLoadingMethod", "AUTOMATION_LOADING_METHOD", ""},
        {"AutomationOldScriptsCompatybility", "AUTOMATION_OLD_SCRIPTS_COMPATIBILITY", ""},
        {"AutomationRecent", "AUTOMATION_RECENT_FILES", ""},
        {"AutomationScriptEditor", "AUTOMATION_SCRIPT_EDITOR", ""},
        {"AutomationTraceLevel", "AUTOMATION_TRACE_LEVEL", ""},
        {"AutoMoveTagsFromOriginal", "AUTO_MOVE_TAGS_FROM_ORIGINAL", ""},
        {"AutoSaveMaxFiles", "AUTOSAVE_MAX_FILES", ""},
        {"AutoSelectLinesFromLastTab", "AUTO_SELECT_LINES_FROM_LAST_TAB", ""},
        {"ColorpickerRecent", "COLORPICKER_RECENT_COLORS", ""},
        {"ConvertASSTagsOnLineStart", "CONVERT_ASS_TAGS_TO_INSERT_IN_LINE", ""},
        {"ConvertFPS", "CONVERT_FPS", ""},
        {"ConvertFPSFromVideo", "CONVERT_FPS_FROM_VIDEO", ""},
        {"ConvertNewEndTimes", "CONVERT_NEW_END_TIMES", ""},
        {"ConvertResolutionWidth", "CONVERT_RESOLUTION_WIDTH", ""},
        {"ConvertResolutionHeight", "CONVERT_RESOLUTION_HEIGHT", ""},
        {"ConvertShowSettings", "CONVERT_SHOW_SETTINGS", ""},
        {"ConvertStyle", "CONVERT_STYLE", ""},
        {"ConvertStyleCatalog", "CONVERT_STYLE_CATALOG", ""},
        {"ConvertTimePerLetter", "CONVERT_TIME_PER_CHARACTER", ""},
        {"CopyCollumnsSelection", "COPY_COLLUMS_SELECTIONS", ""},
        {"DictionaryLanguage", "DICTIONARY_LANGUAGE", ""},
        {"DisableLiveVideoEditing", "DISABLE_LIVE_VIDEO_EDITING", ""},
        {"DontAskForBadResolution", "DONT_ASK_FOR_BAD_RESOLUTION", ""},
        {"EditboxSugestionsOnDoubleClick", "EDITBOX_SUGGESTIONS_ON_DOUBLE_CLICK", ""},
        {"EditorOn", "EDITOR_ON", ""},
        {"FIND_IN_SUBS_FILTERS_RECENT", "FIND_IN_SUBS_FILTERS_RECENT", "\f"},
        {"FIND_IN_SUBS_PATHS_RECENT", "FIND_IN_SUBS_PATHS_RECENT", "\f"},
        {"FindRecent", "FIND_RECENT_FINDS", "\f"},
        {"FindReplaceOptions", "FIND_REPLACE_OPTIONS", ""},
        {"FontCollectorAction", "FONT_COLLECTOR_ACTION", ""},
        {"FontCollectorDirectory", "FONT_COLLECTOR_DIRECTORY", ""},
        {"FontCollectorFromMKV", "FONT_COLLECTOR_FROM_MKV", ""},
        {"FontCollectorUseSubsDirectory", "FONT_COLLECTOR_USE_SUBS_DIRECTORY", ""},
        {"FFMS2VideoSeeking", "FFMS2_VIDEO_SEEKING", ""},
        {"GridChangeActiveOnSelection", "GRID_CHANGE_ACTIVE_ON_SELECTION", ""},
        {"GridFontName", "GRID_FONT", ""},
        {"GridFontSize", "GRID_FONT_SIZE", ""},
        {"GridAddToFilter", "GRID_ADD_TO_FILTER", ""},
        {"GridFilterAfterLoad", "GRID_FILTER_AFTER_LOAD", ""},
        {"GridFilterBy", "GRID_FILTER_BY", ""},
        {"GridFilterInverted", "GRID_FILTER_INVERTED", ""},
        {"GridFilterStyles", "GRID_FILTER_STYLES", ","},
        {"GridHideCollums", "GRID_HIDE_COLUMNS", ""},
        {"GridHideTags", "GRID_HIDE_TAGS", ""},
        {"GridIgnoreFiltering", "GRID_IGNORE_FILTERING", ""},
        {"GridLoadSortedSubs", "GRID_LOAD_SORTED_SUBS", ""},
        {"GridSaveAfterCharacterCount", "GRID_SAVE_AFTER_CHARACTER_COUNT", ""},
        {"GridTagsSwapChar", "GRID_TAGS_SWAP_CHARACTER", ""},
        {"InsertEndOffset", "GRID_INSERT_END_OFFSET", ""},
        {"InsertStartOffset", "GRID_INSERT_START_OFFSET", ""},
        {"KEYFRAMES_RECENT", "KEYFRAMES_RECENT", "|"},
        {"MoveTimesByTime", "SHIFT_TIMES_BY_TIME", ""},
        {"MoveTimesLoadSetTabOptions", "SHIFT_TIMES_CHANGE_VALUES_WITH_TAB", ""},
        {"MoveTimesCorrectEndTimes", "SHIFT_TIMES_CORRECT_END_TIMES", ""},
        {"MoveTimesForward", "SHIFT_TIMES_MOVE_FORWARD", ""},
        {"MoveTimesFrames", "SHIFT_TIMES_DISPLAY_FRAMES", ""},
        {"MoveTimesOn", "SHIFT_TIMES_ON", ""},
        {"MoveTimesOptions", "SHIFT_TIMES_OPTIONS", ""},
        {"MoveTimesWhichLines", "SHIFT_TIMES_WHICH_LINES", ""},
        {"MoveTimesWhichTimes", "SHIFT_TIMES_WHICH_TIMES", ""},
        {"MoveTimesStyles", "SHIFT_TIMES_STYLES", ""},
        {"MoveTimesTime", "SHIFT_TIMES_TIME", ""},
        {"MoveVideoToActiveLine", "MOVE_VIDEO_TO_ACTIVE_LINE", ""},
        {"NoNewLineAfterTimesEdition", "EDITBOX_DONT_GO_TO_NEXT_LINE_ON_TIMES_EDIT", ""},
        {"OpenSubsInNewCard", "OPEN_SUBS_IN_NEW_TAB", ""},
        {"OpenVideoAtActiveLine", "OPEN_VIDEO_AT_ACTIVE_LINE", ""},
        {"PasteCollumnsSelection", "PASTE_COLUMNS_SELECTION", ""},
        {"PlayAfterSelection", "VIDEO_PLAY_AFTER_SELECTION", ""},
        {"PostprocessorEnabling", "POSTPROCESSOR_ON", ""},
        {"PostprocessorKeyframeBeforeStart", "POSTPROCESSOR_KEYFRAME_BEFORE_START", ""},
        {"PostprocessorKeyframeAfterStart", "POSTPROCESSOR_KEYFRAME_AFTER_START", ""},
        {"PostprocessorKeyframeBeforeEnd", "POSTPROCESSOR_KEYFRAME_BEFORE_END", ""},
        {"PostprocessorKeyframeAfterEnd", "POSTPROCESSOR_KEYFRAME_AFTER_END", ""},
        {"PostprocessorLeadIn", "POSTPROCESSOR_LEAD_IN", ""},
        {"PostprocessorLeadOut", "POSTPROCESSOR_LEAD_OUT", ""},
        {"PostprocessorThresholdStart", "POSTPROCESSOR_THRESHOLD_START", ""},
        {"PostprocessorThresholdEnd", "POSTPROCESSOR_THRESHOLD_END", ""},
        {"PreviewText", "STYLE_PREVIEW_TEXT", ""},
        {"ProgramLanguage", "PROGRAM_LANGUAGE", ""},
        {"ProgramTheme", "PROGRAM_THEME", ""},
        {"ReplaceRecent", "REPLACE_RECENT_REPLACEMENTS", "\f"},
        {"SelectionsRecent", "SELECT_LINES_RECENT_SELECTIONS", "\f"},
        {"SelectionsOptions", "SELECT_LINES_OPTIONS", ""},
        {"SelectVisibleLineAfterFullscreen", "GRID_SET_VISIBLE_LINE_AFTER_FULL_SCREEN", ""},
        {"SHIFT_TIMES_PROFILES", "SHIFT_TIMES_PROFILES", "\f"},
        {"SpellcheckerOn", "SPELLCHECKER_ON", ""},
        {"StyleEditFilterText", "STYLE_EDIT_FILTER_TEXT", ""},
        {"StyleFilterTextOn", "STYLE_EDIT_FILTER_TEXT_ON", ""},
        {"StyleManagerPosition", "STYLE_MANAGER_POSITION", ""},
        {"StyleManagerDetachEditor", "STYLE_MANAGER_DETACH_EDIT_WINDOW", ""},
        {"SubsAutonaming", "SUBS_AUTONAMING", ""},
        {"SubsComparisonType", "SUBS_COMPARISON_TYPE", ""},
        {"SubsComparisonStyles", "SUBS_COMPARISON_STYLES", ""},
        {"SubsRecent", "SUBS_RECENT_FILES", "|"},
        {"TextFieldAllowNumpadHotkeys", "TEXT_FIELD_ALLOW_NUMPAD_HOTKEYS", ""},
        {"TlModeShowOriginal", "TL_MODE_SHOW_ORIGINAL", ""},
        {"ToolbarIDs", "TOOLBAR_IDS", "|"},
        {"ToolbarAlignment", "TOOLBAR_ALIGNMENT", ""},
        {"UpdaterCheckForStable", "UPDATER_CHECK_FOR_STABLE", ""},
        {"VideoFullskreenOnStart", "VIDEO_FULL_SCREEN_ON_START", ""},
        {"VideoIndex", "VIDEO_INDEX", ""},
        {"VideoPauseOnClick", "VIDEO_PAUSE_ON_CLICK", ""},
        {"VideoProgressBar", "VIDEO_PROGRESS_BAR", ""},
        {"VideoRecent", "VIDEO_RECENT_FILES", "|"},
        {"VideoVolume", "VIDEO_VOLUME", ""},
        {"VideoWindowSize", "VIDEO_WINDOW_SIZE", ""},
        {"VisualWarningsOff", "VIDEO_VISUAL_WARNINGS_OFF", ""},
        {"WindowMaximized", "WINDOW_MAXIMIZED", ""},
        {"WindowPosition", "WINDOW_POSITION", ""},
        {"WindowSize", "WINDOW_SIZE", ""},
        {"EditboxTagButtons", "EDITBOX_TAG_BUTTONS", ""},
        {"EditboxTagButton1", "EDITBOX_TAG_BUTTON_VALUE1", "\f"},
        {"EditboxTagButton2", "EDITBOX_TAG_BUTTON_VALUE2", "\f"},
        {"EditboxTagButton3", "EDITBOX_TAG_BUTTON_VALUE3", "\f"},
        {"EditboxTagButton4", "EDITBOX_TAG_BUTTON_VALUE4", "\f"},
        {"EditboxTagButton5", "EDITBOX_TAG_BUTTON_VALUE5", "\f"},
        {"EditboxTagButton6", "EDITBOX_TAG_BUTTON_VALUE6", "\f"},
        {"EditboxTagButton7", "EDITBOX_TAG_BUTTON_VALUE7", "\f"},
        {"EditboxTagButton8", "EDITBOX_TAG_BUTTON_VALUE8", "\f"},
        {"EditboxTagButton9", "EDITBOX_TAG_BUTTON_VALUE9", "\f"},
        {"EditboxTagButton10", "EDITBOX_TAG_BUTTON_VALUE10", "\f"},
        {"EditboxTagButton11", "EDITBOX_TAG_BUTTON_VALUE11", "\f"},
        {"EditboxTagButton12", "EDITBOX_TAG_BUTTON_VALUE12", "\f"},
        {"EditboxTagButton13", "EDITBOX_TAG_BUTTON_VALUE13", "\f"},
        {"EditboxTagButton14", "EDITBOX_TAG_BUTTON_VALUE14", "\f"},
        {"EditboxTagButton15", "EDITBOX_TAG_BUTTON_VALUE15", "\f"},
        {"EditboxTagButton16", "EDITBOX_TAG_BUTTON_VALUE16", "\f"},
        {"EditboxTagButton17", "EDITBOX_TAG_BUTTON_VALUE17", "\f"},
        {"EditboxTagButton18", "EDITBOX_TAG_BUTTON_VALUE18", "\f"},
        {"EditboxTagButton19", "EDITBOX_TAG_BUTTON_VALUE19", "\f"},
        {"EditboxTagButton20", "EDITBOX_TAG_BUTTON_VALUE20", "\f"},
    };
    return table;
}

std::span<const NameAlias> colourAliases()
{
    static constexpr NameAlias table[] = {
        {"WindowBackground", "WINDOW_BACKGROUND"},
        {"WindowBackgroundInactive", "WINDOW_BACKGROUND_INACTIVE"},
        {"WindowText", "WINDOW_TEXT"},
        {"WindowTextInactive", "WINDOW_TEXT_INACTIVE"},
        {"WindowBorder", "WINDOW_BORDER"},
        {"WindowBorderInactive", "WINDOW_BORDER_INACTIVE"},
        {"WindowBorderBackground", "WINDOW_BORDER_BACKGROUND"},
        {"WindowBorderBackgroundInactive", "WINDOW_BORDER_BACKGROUND_INACTIVE"},
        {"WindowHeaderText", "WINDOW_HEADER_TEXT"},
        {"WindowHeaderTextInactive", "WINDOW_HEADER_TEXT_INACTIVE"},
        {"WindowHoverHeaderElement", "WINDOW_HOVER_HEADER_ELEMENT"},
        {"WindowPushedHeaderElement", "WINDOW_PUSHED_HEADER_ELEMENT"},
        {"WindowHoverCloseButton", "WINDOW_HOVER_CLOSE_BUTTON"},
        {"WindowPushedCloseButton", "WINDOW_PUSHED_CLOSE_BUTTON"},
        {"WindowWarningElements", "WINDOW_WARNING_ELEMENTS"},
        {"GridText", "GRID_TEXT"},
        {"GridBackground", "GRID_BACKGROUND"},
        {"GridDialogue", "GRID_DIALOGUE"},
        {"GridComment", "GRID_COMMENT"},
        {"GridSelection", "GRID_SELECTION"},
        {"GridVisibleOnVideo", "GRID_LINE_VISIBLE_ON_VIDEO"},
        {"GridCollisions", "GRID_COLLISIONS"},
        {"GridLines", "GRID_LINES"},
        {"GridActiveLine", "GRID_ACTIVE_LINE"},
        {"GridHeader", "GRID_HEADER"},
        {"GridHeaderText", "GRID_HEADER_TEXT"},
        {"GridLabelNormal", "GRID_LABEL_NORMAL"},
        {"GridLabelModified", "GRID_LABEL_MODIFIED"},
        {"GridLabelSaved", "GRID_LABEL_SAVED"},
        {"GridLabelDoubtful", "GRID_LABEL_DOUBTFUL"},
        {"GridSpellchecker", "GRID_SPELLCHECKER"},
        {"GridComparisonOutline", "GRID_COMPARISON_OUTLINE"},
        {"GridComparisonBackgroundNotMatch", "GRID_COMPARISON_BACKGROUND_NOT_MATCH"},
        {"GridComparisonBackgroundMatch", "GRID_COMPARISON_BACKGROUND_MATCH"},
        {"GridComparisonCommentBackgroundNotMatch", "GRID_COMPARISON_COMMENT_BACKGROUND_NOT_MATCH"},
        {"GridComparisonCommentBackgroundMatch", "GRID_COMPARISON_COMMENT_BACKGROUND_MATCH"},
        {"EditorText", "EDITOR_TEXT"},
        {"EditorTagNames", "EDITOR_TAG_NAMES"},
        {"EditorTagValues", "EDITOR_TAG_VALUES"},
        {"EditorCurlyBraces", "EDITOR_CURLY_BRACES"},
        {"EditorTagOperators", "EDITOR_TAG_OPERATORS"},
        {"EditorTemplateVariables", "EDITOR_TEMPLATE_VARIABLES"},
        {"EditorTemplateCodeMarks", "EDITOR_TEMPLATE_CODE_MARKS"},
        {"EditorTemplateFunctions", "EDITOR_TEMPLATE_FUNCTIONS"},
        {"EditorTemplateKeywords", "EDITOR_TEMPLATE_KEYWORDS"},
        {"EditorTemplateStrings", "EDITOR_TEMPLATE_STRINGS"},
        {"EditorPhraseSearch", "EDITOR_PHRASE_SEARCH"},
        {"EditorBracesBackground", "EDITOR_BRACES_BACKGROUND"},
        {"EditorBackground", "EDITOR_BACKGROUND"},
        {"EditorSelection", "EDITOR_SELECTION"},
        {"EditorSelectionNoFocus", "EDITOR_SELECTION_NO_FOCUS"},
        {"EditorBorder", "EDITOR_BORDER"},
        {"EditorBorderOnFocus", "EDITOR_BORDER_ON_FOCUS"},
        {"EditorSpellchecker", "EDITOR_SPELLCHECKER"},
        {"AudioBackground", "AUDIO_BACKGROUND"},
        {"AudioLineBoundaryStart", "AUDIO_LINE_BOUNDARY_START"},
        {"AudioLineBoundaryEnd", "AUDIO_LINE_BOUNDARY_END"},
        {"AudioLineBoundaryMark", "AUDIO_LINE_BOUNDARY_MARK"},
        {"AudioLineBoundaryInactiveLine", "AUDIO_LINE_BOUNDARY_INACTIVE_LINE"},
        {"AudioPlayCursor", "AUDIO_PLAY_CURSOR"},
        {"AudioSecondsBoundaries", "AUDIO_SECONDS_BOUNDARIES"},
        {"AudioKeyframes", "AUDIO_KEYFRAMES"},
        {"AudioSyllableBoundaries", "AUDIO_SYLLABLE_BOUNDARIES"},
        {"AudioSyllableText", "AUDIO_SYLLABLE_TEXT"},
        {"AudioSelectionBackground", "AUDIO_SELECTION_BACKGROUND"},
        {"AudioSelectionBackgroundModified", "AUDIO_SELECTION_BACKGROUND_MODIFIED"},
        {"AudioInactiveLinesBackground", "AUDIO_INACTIVE_LINES_BACKGROUND"},
        {"AudioWaveform", "AUDIO_WAVEFORM"},
        {"AudioWaveformInactive", "AUDIO_WAVEFORM_INACTIVE"},
        {"AudioWaveformModified", "AUDIO_WAVEFORM_MODIFIED"},
        {"AudioWaveformSelected", "AUDIO_WAVEFORM_SELECTED"},
        {"AudioSpectrumBackground", "AUDIO_SPECTRUM_BACKGROUND"},
        {"AudioSpectrumEcho", "AUDIO_SPECTRUM_ECHO"},
        {"AudioSpectrumInner", "AUDIO_SPECTRUM_INNER"},
        {"TextFieldBackground", "TEXT_FIELD_BACKGROUND"},
        {"TextFieldBorder", "TEXT_FIELD_BORDER"},
        {"TextFieldBorderOnFocus", "TEXT_FIELD_BORDER_ON_FOCUS"},
        {"TextFieldSelection", "TEXT_FIELD_SELECTION"},
        {"TextFieldSelectionNoFocus", "TEXT_FIELD_SELECTION_NO_FOCUS"},
        {"ButtonBackground", "BUTTON_BACKGROUND"},
        {"ButtonBackgroundHover", "BUTTON_BACKGROUND_HOVER"},
        {"ButtonBackgroundPushed", "BUTTON_BACKGROUND_PUSHED"},
        {"ButtonBackgroundOnFocus", "BUTTON_BACKGROUND_ON_FOCUS"},
        {"ButtonBorder", "BUTTON_BORDER"},
        {"ButtonBorderHover", "BUTTON_BORDER_HOVER"},
        {"ButtonBorderPushed", "BUTTON_BORDER_PUSHED"},
        {"ButtonBorderOnFocus", "BUTTON_BORDER_ON_FOCUS"},
        {"ButtonBorderInactive", "BUTTON_BORDER_INACTIVE"},
        {"TogglebuttonBackgroundToggled", "TOGGLE_BUTTON_BACKGROUND_TOGGLED"},
        {"TogglebuttonBorderToggled", "TOGGLE_BUTTON_BORDER_TOGGLED"},
        {"ScrollbarBackground", "SCROLLBAR_BACKGROUND"},
        {"ScrollbarScroll", "SCROLLBAR_THUMB"},
        {"ScrollbarScrollHover", "SCROLLBAR_THUMB_HOVER"},
        {"ScrollbarScrollPushed", "SCROLLBAR_THUMB_PUSHED"},
        {"StaticboxBorder", "STATICBOX_BORDER"},
        {"StaticListBorder", "STATICLIST_BORDER"},
        {"StaticListBackground", "STATICLIST_BACKGROUND"},
        {"StaticListSelection", "STATICLIST_SELECTION"},
        {"StaticListBackgroundHeadline", "STATICLIST_BACKGROUND_HEADLINE"},
        {"StaticListTextHeadline", "STATICLIST_TEXT_HEADLINE"},
        {"StatusBarBorder", "STATUSBAR_BORDER"},
        {"MenuBarBackground1", "MENUBAR_BACKGROUND1"},
        {"MenuBarBackground2", "MENUBAR_BACKGROUND2"},
        {"MenuBarBorderSelection", "MENUBAR_BORDER_SELECTION"},
        {"MENU_BAR_BACKGROUND_HOVER", "MENUBAR_BACKGROUND_HOVER"},
        {"MenuBarBackgroundSelection", "MENUBAR_BACKGROUND_SELECTION"},
        {"MenuBackground", "MENUBAR_BACKGROUND"},
        {"MenuBorderSelection", "MENU_BORDER_SELECTION"},
        {"MenuBackgroundSelection", "MENU_BACKGROUND_SELECTION"},
        {"TabsBarBackground1", "TABSBAR_BACKGROUND1"},
        {"TabsBarBackground2", "TABSBAR_BACKGROUND2"},
        {"TabsBorderActive", "TABS_BORDER_ACTIVE"},
        {"TabsBorderInactive", "TABS_BORDER_INACTIVE"},
        {"TabsBackgroundActive", "TABS_BACKGROUND_ACTIVE"},
        {"TabsBackgroundInactive", "TABS_BACKGROUND_INACTIVE"},
        {"TabsBackgroundInactiveHover", "TABS_BACKGROUND_INACTIVE_HOVER"},
        {"TabsBackgroundSecondWindow", "TABS_BACKGROUND_SECOND_WINDOW"},
        {"TabsTextActive", "TABS_TEXT_ACTIVE"},
        {"TabsTextInactive", "TABS_TEXT_INACTIVE"},
        {"TabsCloseHover", "TABS_CLOSE_HOVER"},
        {"TabsBarArrow", "TABSBAR_ARROW"},
        {"TabsBarArrowBackground", "TABSBAR_ARROW_BACKGROUND"},
        {"TabsBarArrowBackgroundHover", "TABSBAR_ARROW_BACKGROUND_HOVER"},
        {"SliderPathBackground", "SLIDER_PATH_BACKGROUND"},
        {"SliderPathBorder", "SLIDER_PATH_BORDER"},
        {"SliderBorder", "SLIDER_BORDER"},
        {"SliderBorderHover", "SLIDER_BORDER_HOVER"},
        {"SliderBorderPushed", "SLIDER_BORDER_PUSHED"},
        {"SliderBackground", "SLIDER_BACKGROUND"},
        {"SliderBackgroundHover", "SLIDER_BACKGROUND_HOVER"},
        {"SliderBackgroundPushed", "SLIDER_BACKGROUND_PUSHED"},
        {"StylePreviewColor1", "STYLE_PREVIEW_COLOR1"},
        {"StylePreviewColor2", "STYLE_PREVIEW_COLOR2"},
    };
    return table;
}

std::span<const NameAlias> hotkeyAliases()
{
    static constexpr NameAlias table[] = {
        {"AudioCommitAlt", "AUDIO_COMMIT_ALT"},
        {"AudioPlayAlt", "AUDIO_PLAY_ALT"},
        {"AudioPlayLineAlt", "AUDIO_PLAY_LINE_ALT"},
        {"AudioPreviousAlt", "AUDIO_PREVIOUS_ALT"},
        {"AudioNextAlt", "AUDIO_NEXT_ALT"},
        {"AudioCommit", "AUDIO_COMMIT"},
        {"AudioPlay", "AUDIO_PLAY"},
        {"AudioPlayLine", "AUDIO_PLAY_LINE"},
        {"AudioPrevious", "AUDIO_PREVIOUS"},
        {"AudioNext", "AUDIO_NEXT"},
        {"AudioStop", "AUDIO_STOP"},
        {"AudioPlayBeforeMark", "AUDIO_PLAY_BEFORE_MARK"},
        {"AudioPlayAfterMark", "AUDIO_PLAY_AFTER_MARK"},
        {"AudioPlay500MSBefore", "AUDIO_PLAY_500MS_BEFORE"},
        {"AudioPlay500MSAfter", "AUDIO_PLAY_500MS_AFTER"},
        {"AudioPlay500MSFirst", "AUDIO_PLAY_500MS_FIRST"},
        {"AudioPlay500MSLast", "AUDIO_PLAY_500MS_LAST"},
        {"AudioPlayToEnd", "AUDIO_PLAY_TO_END"},
        {"AudioScrollLeft", "AUDIO_SCROLL_LEFT"},
        {"AudioScrollRight", "AUDIO_SCROLL_RIGHT"},
        {"AudioGoto", "AUDIO_GOTO"},
        {"AudioLeadin", "AUDIO_LEAD_IN"},
        {"AudioLeadout", "AUDIO_LEAD_OUT"},
        {"PlayPause", "VIDEO_PLAY_PAUSE"},
        {"StopPlayback", "VIDEO_STOP"},
        {"Plus5Second", "VIDEO_5_SECONDS_FORWARD"},
        {"Minus5Second", "VIDEO_5_SECONDS_BACKWARD"},
        {"MinusMinute", "VIDEO_MINUTE_BACKWARD"},
        {"PlusMinute", "VIDEO_MINUTE_FORWARD"},
        {"VolumePlus", "VIDEO_VOLUME_PLUS"},
        {"VolumeMinus", "VIDEO_VOLUME_MINUS"},
        {"PreviousVideo", "VIDEO_PREVIOUS_FILE"},
        {"NextVideo", "VIDEO_NEXT_FILE"},
        {"PreviousChapter", "VIDEO_PREVIOUS_CHAPTER"},
        {"NextChapter", "VIDEO_NEXT_CHAPTER"},
        {"FullScreen", "VIDEO_FULL_SCREEN"},
        {"HideProgressBar", "VIDEO_HIDE_PROGRESS_BAR"},
        {"DeleteVideo", "VIDEO_DELETE_FILE"},
        {"AspectRatio", "VIDEO_ASPECT_RATIO"},
        {"CopyCoords", "VIDEO_COPY_COORDS"},
        {"FrameToPNG", "VIDEO_SAVE_FRAME_TO_PNG"},
        {"FrameToClipboard", "VIDEO_COPY_FRAME_TO_CLIPBOARD"},
        {"SubbedFrameToPNG", "VIDEO_SAVE_SUBBED_FRAME_TO_PNG"},
        {"SubbedFrameToClipboard", "VIDEO_COPY_SUBBED_FRAME_TO_CLIPBOARD"},
        {"PutBold", "EDITBOX_INSERT_BOLD"},
        {"PutItalic", "EDITBOX_INSERT_ITALIC"},
        {"SplitLine", "EDITBOX_SPLIT_LINE"},
        {"StartDifference", "EDITBOX_START_DIFFERENCE"},
        {"EndDifference", "EDITBOX_END_DIFFERENCE"},
        {"FindNextDoubtful", "EDITBOX_FIND_NEXT_DOUBTFUL"},
        {"FindNextUntranslated", "EDITBOX_FIND_NEXT_UNTRANSLATED"},
        {"SetDoubtful", "EDITBOX_SET_DOUBTFUL"},
        {"GRID_FILTER_INVERTED", "GRID_FILTER_INVERT"},
        {"InsertBefore", "GRID_INSERT_BEFORE"},
        {"InsertAfter", "GRID_INSERT_AFTER"},
        {"InsertBeforeVideo", "GRID_INSERT_BEFORE_VIDEO"},
        {"InsertAfterVideo", "GRID_INSERT_AFTER_VIDEO"},
        {"InsertBeforeWithVideoFrame", "GRID_INSERT_BEFORE_WITH_VIDEO_FRAME"},
        {"InsertAfterWithVideoFrame", "GRID_INSERT_AFTER_WITH_VIDEO_FRAME"},
        {"Swap", "GRID_SWAP_LINES"},
        {"Duplicate", "GRID_DUPLICATE_LINES"},
        {"Join", "GRID_JOIN_LINES"},
        {"JoinToFirst", "GRID_JOIN_TO_FIRST_LINE"},
        {"JoinToLast", "GRID_JOIN_TO_LAST_LINE"},
        {"Copy", "GRID_COPY"},
        {"Paste", "GRID_PASTE"},
        {"Cut", "GRID_CUT"},
        {"ShowPreview", "GRID_SHOW_PREVIEW"},
        {"HideSelected", "GRID_HIDE_SELECTED"},
        {"FilterByNothing", "GRID_FILTER_BY_NOTHING"},
        {"FilterByStyles", "GRID_FILTER_BY_STYLES"},
        {"FilterBySelections", "GRID_FILTER_BY_SELECTIONS"},
        {"FilterByDialogues", "GRID_FILTER_BY_DIALOGUES"},
        {"FilterByDoubtful", "GRID_FILTER_BY_DOUBTFUL"},
        {"FilterByUntranslated", "GRID_FILTER_BY_UNTRANSLATED"},
        {"PasteTranslation", "GRID_PASTE_TRANSLATION"},
        {"TranslationDialog", "GRID_TRANSLATION_DIALOG"},
        {"SubsFromMKV", "GRID_SUBS_FROM_MKV"},
        {"ContinousPrevious", "GRID_MAKE_CONTINOUS_PREVIOUS_LINE"},
        {"ContinousNext", "GRID_MAKE_CONTINOUS_NEXT_LINE"},
        {"PasteCollumns", "GRID_PASTE_COLUMNS"},
        {"CopyCollumns", "GRID_COPY_COLUMNS"},
        {"FPSFromVideo", "GRID_SET_FPS_FROM_VIDEO"},
        {"NewFPS", "GRID_SET_NEW_FPS"},
        {"SaveSubs", "GLOBAL_SAVE_SUBS"},
        {"SaveAllSubs", "GLOBAL_SAVE_ALL_SUBS"},
        {"SaveSubsAs", "GLOBAL_SAVE_SUBS_AS"},
        {"SaveTranslation", "GLOBAL_SAVE_TRANSLATION"},
        {"RemoveSubs", "GLOBAL_REMOVE_SUBS"},
        {"Search", "GLOBAL_SEARCH"},
        {"SelectLinesDialog", "GLOBAL_OPEN_SELECT_LINES"},
        {"SpellcheckerDialog", "GLOBAL_OPEN_SPELLCHECKER"},
        {"VideoIndexing", "GLOBAL_VIDEO_INDEXING"},
        {"SaveWithVideoName", "GLOBAL_SAVE_WITH_VIDEO_NAME"},
        {"OpenAudio", "GLOBAL_OPEN_AUDIO"},
        {"AudioFromVideo", "GLOBAL_AUDIO_FROM_VIDEO"},
        {"CloseAudio", "GLOBAL_CLOSE_AUDIO"},
        {"ASSProperties", "GLOBAL_OPEN_ASS_PROPERTIES"},
        {"StyleManager", "GLOBAL_OPEN_STYLE_MANAGER"},
        {"SubsResample", "GLOBAL_OPEN_SUBS_RESAMPLE"},
        {"FontCollectorID", "GLOBAL_OPEN_FONT_COLLECTOR"},
        {"ConvertToASS", "GLOBAL_CONVERT_TO_ASS"},
        {"ConvertToSRT", "GLOBAL_CONVERT_TO_SRT"},
        {"ConvertToTMP", "GLOBAL_CONVERT_TO_TMP"},
        {"ConvertToMDVD", "GLOBAL_CONVERT_TO_MDVD"},
        {"ConvertToMPL2", "GLOBAL_CONVERT_TO_MPL2"},
        {"HideTags", "GLOBAL_HIDE_TAGS"},
        {"ChangeTime", "GLOBAL_SHOW_SHIFT_TIMES"},
        {"ViewAll", "GLOBAL_VIEW_ALL"},
        {"ViewAudio", "GLOBAL_VIEW_AUDIO"},
        {"ViewVideo", "GLOBAL_VIEW_VIDEO"},
        {"ViewSubs", "GLOBAL_VIEW_SUBS"},
        {"AutoLoadScript", "GLOBAL_AUTOMATION_LOAD_SCRIPT"},
        {"AutoReloadAutoload", "GLOBAL_AUTOMATION_RELOAD_AUTOLOAD"},
        {"LoadLastScript", "GLOBAL_AUTOMATION_LOAD_LAST_SCRIPT"},
        {"AUTOMATION_OPEN_HOTKEYS_WINDOW", "GLOBAL_AUTOMATION_OPEN_HOTKEYS_WINDOW"},
        {"PlayPauseG", "GLOBAL_PLAY_PAUSE"},
        {"PreviousFrame", "GLOBAL_PREVIOUS_FRAME"},
        {"NextFrame", "GLOBAL_NEXT_FRAME"},
        {"VideoZoom", "GLOBAL_VIDEO_ZOOM"},
        {"SetStartTime", "GLOBAL_SET_START_TIME"},
        {"SetEndTime", "GLOBAL_SET_END_TIME"},
        {"SetVideoAtStart", "GLOBAL_SET_VIDEO_AT_START_TIME"},
        {"SetVideoAtEnd", "GLOBAL_SET_VIDEO_AT_END_TIME"},
        {"GoToNextKeyframe", "GLOBAL_GO_TO_NEXT_KEYFRAME"},
        {"GoToPrewKeyframe", "GLOBAL_GO_TO_PREVIOUS_KEYFRAME"},
        {"SetAudioFromVideo", "GLOBAL_SET_AUDIO_FROM_VIDEO"},
        {"SetAudioMarkFromVideo", "GLOBAL_SET_AUDIO_MARK_FROM_VIDEO"},
        {"Redo", "GLOBAL_REDO"},
        {"Undo", "GLOBAL_UNDO"},
        {"UndoToLastSave", "GLOBAL_UNDO_TO_LAST_SAVE"},
        {"History", "GLOBAL_HISTORY"},
        {"OpenSubs", "GLOBAL_OPEN_SUBS"},
        {"OpenVideo", "GLOBAL_OPEN_VIDEO"},
        {"GLOBAL_KEYFRAMES_OPEN", "GLOBAL_OPEN_KEYFRAMES"},
        {"Settings", "GLOBAL_SETTINGS"},
        {"Quit", "GLOBAL_QUIT"},
        {"Editor", "GLOBAL_EDITOR"},
        {"About", "GLOBAL_ABOUT"},
        {"Helpers", "GLOBAL_HELPERS"},
        {"Help", "GLOBAL_HELP"},
        {"ANSI", "GLOBAL_ANSI"},
        {"PreviousLine", "GLOBAL_PREVIOUS_LINE"},
        {"NextLine", "GLOBAL_NEXT_LINE"},
        {"JoinWithPrevious", "GLOBAL_JOIN_WITH_PREVIOUS"},
        {"JoinWithNext", "GLOBAL_JOIN_WITH_NEXT"},
        {"NextTab", "GLOBAL_NEXT_TAB"},
        {"PreviousTab", "GLOBAL_PREVIOUS_TAB"},
        {"Remove", "GLOBAL_REMOVE_LINES"},
        {"RemoveText", "GLOBAL_REMOVE_TEXT"},
        {"SnapWithStart", "GLOBAL_SNAP_WITH_START"},
        {"SnapWithEnd", "GLOBAL_SNAP_WITH_END"},
        {"Plus5SecondG", "GLOBAL_5_SECONDS_FORWARD"},
        {"Minus5SecondG", "GLOBAL_5_SECONDS_BACKWARD"},
        {"SortLines", "GLOBAL_SORT_LINES"},
        {"SortSelected", "GLOBAL_SORT_SELECTED_LINES"},
        {"RecentAudio", "GLOBAL_RECENT_AUDIO"},
        {"RecentVideo", "GLOBAL_RECENT_VIDEO"},
        {"RecentSubs", "GLOBAL_RECENT_SUBS"},
        {"GLOBAL_KEYFRAMES_RECENT", "GLOBAL_RECENT_KEYFRAMES"},
        {"SelectFromVideo", "GLOBAL_SELECT_FROM_VIDEO"},
        {"PlayActualLine", "GLOBAL_PLAY_ACTUAL_LINE"},
    };
    return table;
}

std::span<const std::string_view> themeColourKeys()
{
    static constexpr std::string_view table[] = {
        "WINDOW_BACKGROUND",
        "WINDOW_BACKGROUND_INACTIVE",
        "WINDOW_TEXT",
        "WINDOW_TEXT_INACTIVE",
        "WINDOW_BORDER",
        "WINDOW_BORDER_INACTIVE",
        "WINDOW_BORDER_BACKGROUND",
        "WINDOW_BORDER_BACKGROUND_INACTIVE",
        "WINDOW_HEADER_TEXT",
        "WINDOW_HEADER_TEXT_INACTIVE",
        "WINDOW_HOVER_HEADER_ELEMENT",
        "WINDOW_PUSHED_HEADER_ELEMENT",
        "WINDOW_HOVER_CLOSE_BUTTON",
        "WINDOW_PUSHED_CLOSE_BUTTON",
        "WINDOW_WARNING_ELEMENTS",
        "GRID_TEXT",
        "GRID_BACKGROUND",
        "GRID_DIALOGUE",
        "GRID_COMMENT",
        "GRID_SELECTION",
        "GRID_LINE_VISIBLE_ON_VIDEO",
        "GRID_COLLISIONS",
        "GRID_LINES",
        "GRID_ACTIVE_LINE",
        "GRID_HEADER",
        "GRID_HEADER_TEXT",
        "GRID_LABEL_NORMAL",
        "GRID_LABEL_MODIFIED",
        "GRID_LABEL_SAVED",
        "GRID_LABEL_DOUBTFUL",
        "GRID_SPELLCHECKER",
        "GRID_COMPARISON_OUTLINE",
        "GRID_COMPARISON_BACKGROUND_NOT_MATCH",
        "GRID_COMPARISON_BACKGROUND_MATCH",
        "GRID_COMPARISON_COMMENT_BACKGROUND_NOT_MATCH",
        "GRID_COMPARISON_COMMENT_BACKGROUND_MATCH",
        "EDITOR_TEXT",
        "EDITOR_TAG_NAMES",
        "EDITOR_TAG_VALUES",
        "EDITOR_CURLY_BRACES",
        "EDITOR_TAG_OPERATORS",
        "EDITOR_SPLIT_LINES_AND_DRAWINGS",
        "EDITOR_TEMPLATE_VARIABLES",
        "EDITOR_TEMPLATE_CODE_MARKS",
        "EDITOR_TEMPLATE_FUNCTIONS",
        "EDITOR_TEMPLATE_KEYWORDS",
        "EDITOR_TEMPLATE_STRINGS",
        "EDITOR_PHRASE_SEARCH",
        "EDITOR_BRACES_BACKGROUND",
        "EDITOR_BACKGROUND",
        "EDITOR_SELECTION",
        "EDITOR_SELECTION_NO_FOCUS",
        "EDITOR_BORDER",
        "EDITOR_BORDER_ON_FOCUS",
        "EDITOR_SPELLCHECKER",
        "AUDIO_BACKGROUND",
        "AUDIO_LINE_BOUNDARY_START",
        "AUDIO_LINE_BOUNDARY_END",
        "AUDIO_LINE_BOUNDARY_MARK",
        "AUDIO_LINE_BOUNDARY_INACTIVE_LINE",
        "AUDIO_PLAY_CURSOR",
        "AUDIO_SECONDS_BOUNDARIES",
        "AUDIO_KEYFRAMES",
        "AUDIO_SYLLABLE_BOUNDARIES",
        "AUDIO_SYLLABLE_TEXT",
        "AUDIO_SELECTION_BACKGROUND",
        "AUDIO_SELECTION_BACKGROUND_MODIFIED",
        "AUDIO_INACTIVE_LINES_BACKGROUND",
        "AUDIO_WAVEFORM",
        "AUDIO_WAVEFORM_INACTIVE",
        "AUDIO_WAVEFORM_MODIFIED",
        "AUDIO_WAVEFORM_SELECTED",
        "AUDIO_SPECTRUM_BACKGROUND",
        "AUDIO_SPECTRUM_ECHO",
        "AUDIO_SPECTRUM_INNER",
        "TEXT_FIELD_BACKGROUND",
        "TEXT_FIELD_BORDER",
        "TEXT_FIELD_BORDER_ON_FOCUS",
        "TEXT_FIELD_SELECTION",
        "TEXT_FIELD_SELECTION_NO_FOCUS",
        "BUTTON_BACKGROUND",
        "BUTTON_BACKGROUND_HOVER",
        "BUTTON_BACKGROUND_PUSHED",
        "BUTTON_BACKGROUND_ON_FOCUS",
        "BUTTON_BORDER",
        "BUTTON_BORDER_HOVER",
        "BUTTON_BORDER_PUSHED",
        "BUTTON_BORDER_ON_FOCUS",
        "BUTTON_BORDER_INACTIVE",
        "TOGGLE_BUTTON_BACKGROUND_TOGGLED",
        "TOGGLE_BUTTON_BORDER_TOGGLED",
        "SCROLLBAR_BACKGROUND",
        "SCROLLBAR_THUMB",
        "SCROLLBAR_THUMB_HOVER",
        "SCROLLBAR_THUMB_PUSHED",
        "STATICBOX_BORDER",
        "STATICLIST_BORDER",
        "STATICLIST_BACKGROUND",
        "STATICLIST_SELECTION",
        "STATICLIST_BACKGROUND_HEADLINE",
        "STATICLIST_TEXT_HEADLINE",
        "STATUSBAR_BORDER",
        "MENUBAR_BACKGROUND1",
        "MENUBAR_BACKGROUND2",
        "MENUBAR_BORDER_SELECTION",
        "MENUBAR_BACKGROUND_HOVER",
        "MENUBAR_BACKGROUND_SELECTION",
        "MENUBAR_BACKGROUND",
        "MENU_BORDER_SELECTION",
        "MENU_BACKGROUND_SELECTION",
        "TABSBAR_BACKGROUND1",
        "TABSBAR_BACKGROUND2",
        "TABS_BORDER_ACTIVE",
        "TABS_BORDER_INACTIVE",
        "TABS_BACKGROUND_ACTIVE",
        "TABS_BACKGROUND_INACTIVE",
        "TABS_BACKGROUND_INACTIVE_HOVER",
        "TABS_BACKGROUND_SECOND_WINDOW",
        "TABS_TEXT_ACTIVE",
        "TABS_TEXT_INACTIVE",
        "TABS_CLOSE_HOVER",
        "TABSBAR_ARROW",
        "TABSBAR_ARROW_BACKGROUND",
        "TABSBAR_ARROW_BACKGROUND_HOVER",
        "SLIDER_PATH_BACKGROUND",
        "SLIDER_PATH_BORDER",
        "SLIDER_BORDER",
        "SLIDER_BORDER_HOVER",
        "SLIDER_BORDER_PUSHED",
        "SLIDER_BACKGROUND",
        "SLIDER_BACKGROUND_HOVER",
        "SLIDER_BACKGROUND_PUSHED",
        "WINDOW_RESIZER_DOTS",
        "FIND_RESULT_FILENAME_FOREGROUND",
        "FIND_RESULT_FILENAME_BACKGROUND",
        "FIND_RESULT_FOUND_PHRASE_FOREGROUND",
        "FIND_RESULT_FOUND_PHRASE_BACKGROUND",
        "STYLE_PREVIEW_COLOR1",
        "STYLE_PREVIEW_COLOR2",
    };
    return table;
}

// config::LoadDefaultConfig (config.cpp:346-390) and LoadDefaultAudioConfig
// (config.cpp:806-838): the options their defaults assign.
std::span<const std::string_view> mainDefaultKeys()
{
    static constexpr std::string_view table[] = {
        "AUDIO_BOX_HEIGHT",
        "SHIFT_TIMES_TIME",
        "SHIFT_TIMES_WHICH_LINES",
        "CONVERT_RESOLUTION_WIDTH",
        "CONVERT_RESOLUTION_HEIGHT",
        "CONVERT_FPS",
        "CONVERT_STYLE",
        "CONVERT_STYLE_CATALOG",
        "DICTIONARY_LANGUAGE",
        "SPELLCHECKER_ON",
        "STYLE_EDIT_FILTER_TEXT",
        "FFMS2_VIDEO_SEEKING",
        "SHIFT_TIMES_BY_TIME",
        "GRID_FONT",
        "GRID_FONT_SIZE",
        "PROGRAM_FONT",
        "PROGRAM_FONT_SIZE",
        "GRID_SAVE_AFTER_CHARACTER_COUNT",
        "GRID_TAGS_SWAP_CHARACTER",
        "SHIFT_TIMES_MOVE_FORWARD",
        "CONVERT_NEW_END_TIMES",
        "GRID_INSERT_START_OFFSET",
        "GRID_INSERT_END_OFFSET",
        "VIDEO_PLAY_AFTER_SELECTION",
        "STYLE_PREVIEW_TEXT",
        "PROGRAM_THEME",
        "EDITOR_ON",
        "CONVERT_SHOW_SETTINGS",
        "SHIFT_TIMES_ON",
        "SHIFT_TIMES_WHICH_TIMES",
        "SHIFT_TIMES_STYLES",
        "CONVERT_TIME_PER_CHARACTER",
        "VIDEO_INDEX",
        "VIDEO_GPU_CONVERSION",
        "VIDEO_PROGRESS_BAR",
        "VIDEO_WINDOW_SIZE",
        "WINDOW_SIZE",
        "AUTOMATION_TRACE_LEVEL",
        "AUTOSAVE_MAX_FILES",
        "GRID_CHANGE_ACTIVE_ON_SELECTION",
        "UPDATER_CHECK_FOR_STABLE",
    };
    return table;
}

std::span<const std::string_view> audioDefaultKeys()
{
    static constexpr std::string_view table[] = {
        "AUDIO_AUTO_COMMIT",
        "AUDIO_AUTO_FOCUS",
        "AUDIO_AUTO_SCROLL",
        "AUDIO_CACHE_FILES_LIMIT",
        "AUDIO_DELAY",
        "AUDIO_DRAW_TIME_CURSOR",
        "AUDIO_DRAW_KEYFRAMES",
        "AUDIO_DRAW_SECONDARY_LINES",
        "AUDIO_DRAW_SELECTION_BACKGROUND",
        "AUDIO_DRAW_VIDEO_POSITION",
        "AUDIO_GRAB_TIMES_ON_SELECT",
        "AUDIO_HORIZONTAL_ZOOM",
        "AUDIO_INACTIVE_LINES_DISPLAY_MODE",
        "AUDIO_KARAOKE",
        "AUDIO_KARAOKE_SPLIT_MODE",
        "AUDIO_LEAD_IN_VALUE",
        "AUDIO_LEAD_OUT_VALUE",
        "AUDIO_LINE_BOUNDARIES_THICKNESS",
        "AUDIO_LINK",
        "AUDIO_LOCK_SCROLL_ON_CURSOR",
        "AUDIO_MARK_PLAY_TIME",
        "AUDIO_NEXT_LINE_ON_COMMIT",
        "AUDIO_RAM_CACHE",
        "AUDIO_SNAP_TO_KEYFRAMES",
        "AUDIO_SNAP_TO_OTHER_LINES",
        "AUDIO_SPECTRUM_ON",
        "AUDIO_START_DRAG_SENSITIVITY",
        "AUDIO_VERTICAL_ZOOM",
        "AUDIO_VOLUME",
        "AUDIO_WHEEL_DEFAULT_TO_ZOOM",
    };
    return table;
}

} // namespace hikari::application::settings_import
