# Module boundary enforcement (docs/qt/architecture.md). Each module declares
# the targets it may link; the check runs at configure time and fails on any
# other hikari_*, Hikari::* or Qt6::* dependency. Entries may end in '*'.
include_guard(GLOBAL)

set_property(GLOBAL PROPERTY HIKARI_MODULES "")

function(hikari_module target)
    cmake_parse_arguments(arg "" "" "ALLOW" ${ARGN})
    set_property(GLOBAL APPEND PROPERTY HIKARI_MODULES ${target})
    set_property(TARGET ${target} PROPERTY HIKARI_ALLOWED_LINKS "${arg_ALLOW}")
endfunction()

# Pure check, also used by the controlled-violation test in script mode.
function(hikari_module_violations links allowed out_var)
    set(bad "")
    foreach(link IN LISTS links)
        string(REGEX REPLACE "^\\$<LINK_ONLY:(.*)>$" "\\1" link "${link}")
        if(NOT link MATCHES "^(hikari_|Hikari::|Qt6::)")
            continue()
        endif()
        set(ok FALSE)
        foreach(pattern IN LISTS allowed)
            if(pattern MATCHES "\\*$")
                string(REGEX REPLACE "\\*$" "" prefix "${pattern}")
                string(FIND "${link}" "${prefix}" pos)
                if(pos EQUAL 0)
                    set(ok TRUE)
                endif()
            elseif(link STREQUAL pattern)
                set(ok TRUE)
            endif()
        endforeach()
        if(NOT ok)
            list(APPEND bad "${link}")
        endif()
    endforeach()
    set(${out_var} "${bad}" PARENT_SCOPE)
endfunction()

function(hikari_check_module_dependencies)
    get_property(modules GLOBAL PROPERTY HIKARI_MODULES)
    foreach(target IN LISTS modules)
        get_target_property(links ${target} LINK_LIBRARIES)
        get_target_property(iface ${target} INTERFACE_LINK_LIBRARIES)
        foreach(v links iface)
            if(NOT ${v})
                set(${v} "")
            endif()
        endforeach()
        get_target_property(allowed ${target} HIKARI_ALLOWED_LINKS)
        hikari_module_violations("${links};${iface}" "${allowed}" bad)
        list(REMOVE_DUPLICATES bad)
        if(bad)
            message(FATAL_ERROR "Module ${target} must not depend on: ${bad} (see docs/qt/architecture.md)")
        endif()
    endforeach()
endfunction()
